// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

namespace Zitadel.Client;

/// <summary>
/// Interface for API HTTP transport.
/// </summary>
public interface IApiClient
{
    /// <summary>
    /// Send an HTTP request and return the response.
    /// </summary>
    /// <param name="method">HTTP method (GET, POST, PUT, DELETE, etc.)</param>
    /// <param name="url">Fully qualified URL</param>
    /// <param name="headers">HTTP headers</param>
    /// <param name="body">Request body (JSON string, byte[], Stream, Dictionary for multipart, or null)</param>
    /// <param name="noRedirect">
    /// When <c>true</c>, the transport must NOT follow 3xx redirects on this call
    /// and must surface a 307/308 response as-is. Used by the OAuth2 token
    /// exchange so that a malicious 307 from a token endpoint cannot silently
    /// replay client credentials to an attacker-controlled host (Gap 3.2).
    /// Default <c>false</c> preserves the existing redirect-following behaviour.
    /// </param>
    /// <returns>ApiHttpResponse containing status code, body, and headers</returns>
    Task<ApiHttpResponse> SendRequestAsync(
        string method,
        Uri url,
        Dictionary<string, string> headers,
        object? body,
        bool noRedirect = false
    );
}
