// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

namespace Zitadel.Client;

/// <summary>
/// Exception thrown when an API call fails.
/// </summary>
public class ApiException : ZitadelException
{
    public int StatusCode { get; }
    public string? ResponseBody { get; }
    public Dictionary<string, string>? ResponseHeaders { get; }
    public object? ErrorBody { get; }

    public ApiException() { }

    public ApiException(string message)
        : base(message) { }

    public ApiException(string message, Exception innerException)
        : base(message, innerException) { }

    public ApiException(
        int statusCode,
        string message,
        Dictionary<string, string>? responseHeaders = null,
        string? responseBody = null,
        object? errorBody = null
    )
        : base(message)
    {
        StatusCode = statusCode;
        ResponseHeaders = responseHeaders;
        ResponseBody = responseBody;
        ErrorBody = errorBody;
    }

    public T? GetTypedErrorBody<T>()
        where T : class
    {
        return ErrorBody as T;
    }

    public override string ToString()
    {
        return $"ApiException{{StatusCode={StatusCode}, ResponseBody='{ResponseBody}'}}";
    }
}
