// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Collections.ObjectModel;

namespace Zitadel.Client;

/// <summary>
/// Represents an HTTP API response.
/// </summary>
public class ApiHttpResponse(
    int statusCode,
    string body,
    IReadOnlyDictionary<string, string> headers
)
{
    /// <summary>The HTTP status code.</summary>
    public int StatusCode { get; } = statusCode;

    /// <summary>The raw response body string.</summary>
    public string Body { get; } = body;

    /// <summary>The response headers (unmodifiable).</summary>
    /* Defensive copy wrapped read-only, matching ApiResult: the caller's
       dictionary cannot mutate the response headers after construction. */
    public IReadOnlyDictionary<string, string> Headers { get; } =
        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>(headers));
}
