// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

namespace Zitadel.Client;

/// <summary>
/// Represents an HTTP API response.
/// </summary>
public class ApiHttpResponse(
    int statusCode,
    string body,
    IReadOnlyDictionary<string, string> headers
)
{
    public int StatusCode { get; } = statusCode;
    public string Body { get; } = body;
    public IReadOnlyDictionary<string, string> Headers { get; } = headers;
}
