// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.RegularExpressions;

namespace Zitadel.Client;

/// <summary>
/// Selects appropriate Content-Type and Accept headers for API requests.
/// </summary>
internal static partial class HeaderSelector
{
    [GeneratedRegex(@"^application/(json|[\w!#$&.+\-^_]+\+json)\s*(;|$)", RegexOptions.IgnoreCase)]
    private static partial Regex JsonMimePattern();

    /// <summary>
    /// Select headers for an API request.
    /// </summary>
    public static Dictionary<string, string> SelectHeaders(
        string[] accept,
        string contentType,
        bool isMultipart
    )
    {
        Dictionary<string, string> headers = [];

        string? acceptHeader = SelectAcceptHeader(accept);
        if (acceptHeader != null)
        {
            headers["Accept"] = acceptHeader;
        }

        if (!isMultipart)
        {
            if (string.IsNullOrEmpty(contentType))
            {
                contentType = "application/json";
            }
            headers["Content-Type"] = contentType;
        }

        return headers;
    }

    /// <summary>
    /// Check if a MIME type is a JSON type.
    /// </summary>
    public static bool IsJsonMime(string? mimeType)
    {
        return mimeType != null && JsonMimePattern().IsMatch(mimeType);
    }

    private static string? SelectAcceptHeader(string[]? accept)
    {
        if (accept == null || accept.Length == 0)
        {
            return null;
        }

        string[] filtered = [.. accept.Where(s => !string.IsNullOrWhiteSpace(s))];
        if (filtered.Length == 0)
        {
            return string.Empty;
        }

        return string.Join(", ", filtered);
    }
}
