// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using Zitadel.Client.Errors;
using System.Collections;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client;

/// <summary>
/// Handles JSON serialization and deserialization for API requests and responses.
/// </summary>
internal class ObjectSerializer
{
    private readonly JsonSerializerOptions _options;

    public ObjectSerializer()
    {
        _options = CreateDefaultOptions();
    }

    /// <summary>
    /// Serialize an object to a JSON string.
    /// Unwraps a oneOf wrapper by serializing its single <c>ActualInstance</c>.
    /// An anyOf wrapper (identified by a <c>MatchedInstances</c> property) is
    /// serialized through its own converter instead, so the inclusive union of
    /// every retained variant's fields is emitted and a co-satisfied payload
    /// round-trips losslessly rather than collapsing to the first variant.
    /// </summary>
    /// <exception cref="SerializationException">
    /// Thrown when the value cannot be serialized to JSON. The underlying
    /// <see cref="JsonException"/> (or other native serializer failure) is
    /// preserved as the inner exception so the SDK never leaks
    /// <c>System.Text.Json</c> types out of its public surface.
    /// </exception>
    public string Serialize(object? value)
    {
        if (value != null)
        {
            System.Type valueType = value.GetType();
            /* An anyOf wrapper carries a MatchedInstances list and must be
             * serialized through its own JsonConverter so the union of every
             * retained variant's fields is emitted. Unwrapping it to a single
             * ActualInstance here would drop the co-matched variants' data. */
            bool isAnyOfWrapper = valueType.GetProperty("MatchedInstances") != null;
            if (!isAnyOfWrapper)
            {
                System.Reflection.PropertyInfo? actualProp = valueType
                    .GetProperty("ActualInstance");
                if (actualProp != null)
                {
                    value = actualProp.GetValue(value);
                }
            }
        }
        try
        {
            return JsonSerializer.Serialize(value, _options);
        }
        catch (JsonException e)
        {
            throw new SerializationException("Failed to serialize object to JSON", e);
        }
        catch (NotSupportedException e)
        {
            throw new SerializationException("Failed to serialize object to JSON", e);
        }
    }

    /// <summary>
    /// Deserialize a JSON string to an object of the specified type.
    /// </summary>
    /// <exception cref="SerializationException">
    /// Thrown when the JSON is malformed or does not match the target type.
    /// The underlying <see cref="JsonException"/> (or other native
    /// serializer failure) is preserved as the inner exception so the SDK
    /// never leaks <c>System.Text.Json</c> types out of its public surface.
    /// </exception>
    public T? Deserialize<T>(string? json)
    {
        if (string.IsNullOrEmpty(json))
        {
            return default;
        }
        /* utf8-bom-strip: System.Text.Json does not strip a leading UTF-8 BOM
         * (U+FEFF) from string input, so a BOM-prefixed body would throw a
         * JsonException on the very first token. Strip it before parsing to
         * match the other language SDKs, which all tolerate a leading BOM. */
        if (json[0] == '\uFEFF')
        {
            json = json[1..];
        }
        try
        {
            return JsonSerializer.Deserialize<T>(json, _options);
        }
        catch (JsonException e)
        {
            throw new SerializationException(
                $"Failed to deserialize JSON to {typeof(T)}",
                e
            );
        }
        catch (NotSupportedException e)
        {
            throw new SerializationException(
                $"Failed to deserialize JSON to {typeof(T)}",
                e
            );
        }
        catch (Exception e) when (e is FormatException or OverflowException)
        {
            /* A converter that parses a scalar (date, number, duration) must
               never leak the BCL parse failure: it is a wire-shape error. */
            throw new SerializationException(
                $"Failed to deserialize JSON to {typeof(T)}",
                e
            );
        }
    }

    /// <summary>
    /// Convert a scalar value to its canonical string representation.
    /// Booleans are lowercased, date/time values use ISO 8601 round-trip format,
    /// <see cref="TimeOnly"/> uses HH:mm:ss (OAS <c>format:time</c>),
    /// <see cref="TimeSpan"/> uses protobuf-JSON duration form (OAS <c>format:duration</c>),
    /// and null values return an empty string.
    /// </summary>
    public static string Stringify(object? value)
    {
        return value switch
        {
            null => "",
            bool b => b ? "true" : "false",
            DateOnly d => d.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture),
            TimeOnly t => t.ToString("HH:mm:ss", System.Globalization.CultureInfo.InvariantCulture),
            TimeSpan ts => ProtobufDurationConverter.Format(ts),
            DateTimeOffset dto => dto.ToString("yyyy-MM-dd'T'HH:mm:ss.fffzzz", System.Globalization.CultureInfo.InvariantCulture),
            DateTime dt => new DateTimeOffset(dt.Kind == DateTimeKind.Unspecified ? DateTime.SpecifyKind(dt, DateTimeKind.Utc) : dt).ToString("yyyy-MM-dd'T'HH:mm:ss.fffzzz", System.Globalization.CultureInfo.InvariantCulture),
            Enum e => StringifyEnum(e),
            IFormattable f => f.ToString(null, System.Globalization.CultureInfo.InvariantCulture),
            _ => value.ToString() ?? "",
        };
    }

    /// <summary>
    /// Stringifies an enum to its OpenAPI wire value (not the C# member name)
    /// for use in query, path, and header parameters. The generated
    /// <c>[JsonConverter]</c> on each enum maps members to their wire strings,
    /// so the value is serialized through it and the surrounding JSON quotes
    /// are stripped. Enums without a string converter (e.g. integer enums)
    /// serialize to their numeric form, which is itself the wire value.
    /// </summary>
    private static string StringifyEnum(Enum value)
    {
        string json = JsonSerializer.Serialize(value, value.GetType());
        return json.Length >= 2 && json[0] == '"' && json[^1] == '"'
            ? json[1..^1]
            : json;
    }

    /// <summary>
    /// Convert a value to a string suitable for use as a URL path parameter.
    /// </summary>
    public static string ToPathValue(object? value)
    {
        return Stringify(value);
    }

    /// <summary>
    /// Convert a value to a representation suitable for use as a query parameter.
    /// </summary>
    public static object? ToQueryValue(object? value, string? collectionFormat)
    {
        if (value == null)
        {
            return null;
        }
        if (value is IList list)
        {
            List<string> items = [];
            foreach (object? item in list)
            {
                items.Add(Stringify(item));
            }
            if (collectionFormat == "multi")
            {
                return items;
            }
            string sep = collectionFormat switch
            {
                "ssv" => " ",
                "tsv" => "\t",
                "pipes" => "|",
                _ => ",",
            };
            return string.Join(sep, items);
        }
        return Stringify(value);
    }

    /// <summary>
    /// Convert a value to a string suitable for use as an HTTP header value.
    /// </summary>
    public static string ToHeaderValue(object? value)
    {
        if (value == null)
        {
            return "";
        }
        if (value is IList list)
        {
            List<string> items = [];
            foreach (object? item in list)
            {
                items.Add(Stringify(item));
            }
            return string.Join(",", items);
        }
        return Stringify(value);
    }

    /// <summary>
    /// Convert a value to a string suitable for use as an HTTP cookie value.
    /// Cookie values follow the same encoding rules as header values.
    /// </summary>
    public static string ToCookieValue(object? value)
    {
        return ToHeaderValue(value);
    }

    /// <summary>
    /// Convert a value to a representation suitable for use as a form parameter.
    /// </summary>
    public static string ToFormValue(object? value)
    {
        return Stringify(value);
    }

    /// <summary>
    /// Resolve a oneOf schema by attempting deserialization against each candidate.
    /// Each candidate is a function that accepts a parsed <see cref="JsonElement"/>
    /// and returns a deserialized value, or throws on failure.
    /// Returns the first successful deserialization result, or throws a
    /// <see cref="JsonException"/> when no candidate matches — a payload that
    /// satisfies none of the declared variants is a contract violation and must
    /// fail loudly rather than be silently dropped to null.
    /// </summary>
    internal static object ResolveOneOf(JsonElement json, params Func<JsonElement, object?>[] candidates)
    {
        ArgumentNullException.ThrowIfNull(candidates);

        foreach (Func<JsonElement, object?> candidate in candidates)
        {
            try
            {
                object? result = candidate(json);
                if (result != null)
                {
                    return result;
                }
            }
            catch (JsonException)
            {
            }
            catch (NotSupportedException)
            {
            }
        }

        throw new JsonException("No oneOf/anyOf variant matched the JSON");
    }

    /// <summary>
    /// Resolve an anyOf schema by attempting deserialization against each candidate.
    /// Each candidate is a function that accepts a parsed <see cref="JsonElement"/>
    /// and returns a deserialized value, or throws on failure.
    /// Returns the first successful deserialization result, or throws a
    /// <see cref="JsonException"/> when no candidate matches.
    /// </summary>
    internal static object ResolveAnyOf(JsonElement json, params Func<JsonElement, object?>[] candidates)
    {
        return ResolveOneOf(json, candidates);
    }

    private static JsonSerializerOptions CreateDefaultOptions()
    {
        JsonSerializerOptions options = new()
        {
            PropertyNamingPolicy = null,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            WriteIndented = false,
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
            /* Pin the reflection-based metadata resolver. When a consuming app
             * is published with PublishTrimmed (Release Blazor WebAssembly,
             * single-file, ...), the trimmer disables reflection serialization
             * by default, which would make every Serialize/Deserialize throw
             * "reflection-based serialization has been disabled". The model
             * members themselves are preserved by the embedded
             * ILLink.Descriptors.xml keep-list, so reflection is safe here. */
            TypeInfoResolver = new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver(),
        };
        /* No global JsonStringEnumConverter: every generated enum carries its
         * own [JsonConverter(typeof(XxxConverter))] that maps to the exact
         * OpenAPI wire value (e.g. "available"). System.Text.Json ranks an
         * options-registered converter ABOVE a type-level [JsonConverter]
         * attribute, so a global string-enum converter here would shadow those
         * per-enum converters on the write path and emit the C# member name
         * ("Available") instead of the wire value. The per-enum converters
         * cover every enum, so no global fallback is needed. */
        options.Converters.Add(new DateTimeOffsetJsonConverter());
        /* 4.8: TimeSpan's default System.Text.Json form is the .NET
         * "[d.]hh:mm:ss[.fff]" string, which would not round-trip with
         * any other language SDK. Register the protobuf-JSON duration
         * converter so format:duration values are emitted as
         * "3600s"-style strings matching protobuf's canonical JSON
         * mapping (the wire format a gRPC-gateway expects). */
        options.Converters.Add(new ProtobufDurationConverter());
        return options;
    }

    /// <summary>
    /// Serializes DateTimeOffset values as ISO 8601 strings with millisecond
    /// precision, matching the format used by all other language generators:
    /// yyyy-MM-dd'T'HH:mm:ss.fffzzz. Millisecond (3-digit) sub-second precision
    /// is emitted so the fraction the reader accepts is also written, keeping
    /// the round-trip lossless instead of truncating to whole seconds.
    /// </summary>
    private sealed class DateTimeOffsetJsonConverter : System.Text.Json.Serialization.JsonConverter<DateTimeOffset>
    {
        private const string Format = "yyyy-MM-dd'T'HH:mm:ss.fffzzz";

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            /* A malformed date-time is a wire-shape failure: raise JsonException
               (wrapped as SerializationException by Deserialize) rather than
               letting DateTimeOffset.Parse leak a raw FormatException. */
            if (reader.TokenType != JsonTokenType.String)
            {
                throw new JsonException($"Expected a JSON string for a date-time but got {reader.TokenType}.");
            }
            string text = reader.GetString()!;
            if (!DateTimeOffset.TryParse(
                    text,
                    System.Globalization.CultureInfo.InvariantCulture,
                    System.Globalization.DateTimeStyles.None,
                    out DateTimeOffset value))
            {
                throw new JsonException($"Invalid date-time: {text}");
            }
            return value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString(Format, System.Globalization.CultureInfo.InvariantCulture));
        }
    }

    /// <summary>
    /// Structural value-equality for model fields. Scalars and model instances
    /// compare via <see cref="object.Equals(object?)"/>; collections compare
    /// element-wise (recursively), and <c>byte[]</c> compares by content, so two
    /// instances deserialized from identical JSON are equal even when a field is
    /// a list, set, map, or byte array. Used by generated model
    /// <c>Equals</c>/<c>GetHashCode</c> so models work as HashSet/Dictionary keys.
    /// </summary>
    public static bool StructuralEquals(object? left, object? right)
    {
        if (ReferenceEquals(left, right))
        {
            return true;
        }

        if (left is null || right is null)
        {
            return false;
        }

        if (left is byte[] leftBytes && right is byte[] rightBytes)
        {
            return leftBytes.AsSpan().SequenceEqual(rightBytes);
        }

        if (left is IDictionary leftDict && right is IDictionary rightDict)
        {
            if (leftDict.Count != rightDict.Count)
            {
                return false;
            }

            foreach (DictionaryEntry entry in leftDict)
            {
                if (!rightDict.Contains(entry.Key)
                    || !StructuralEquals(entry.Value, rightDict[entry.Key]))
                {
                    return false;
                }
            }

            return true;
        }

        /* Set-typed fields (e.g. HashSet<T>) have no defined enumeration
           order, so element-wise comparison would report equal sets as unequal
           when the same items were inserted in a different order. Compare them
           by order-independent membership instead, mirroring the dictionary
           path above. Both sides must be sets for set semantics to apply. */
        if (IsSet(left) && IsSet(right))
        {
            return SetStructuralEquals((IEnumerable)left, (IEnumerable)right);
        }

        /* Strings are IEnumerable but must compare as scalars, so they fall
           through to object.Equals below. */
        if (left is IEnumerable leftSeq && right is IEnumerable rightSeq
            && left is not string && right is not string)
        {
            IEnumerator leftEnum = leftSeq.GetEnumerator();
            IEnumerator rightEnum = rightSeq.GetEnumerator();
            try
            {
                while (true)
                {
                    bool leftHasNext = leftEnum.MoveNext();
                    bool rightHasNext = rightEnum.MoveNext();
                    if (leftHasNext != rightHasNext)
                    {
                        return false;
                    }

                    if (!leftHasNext)
                    {
                        return true;
                    }

                    if (!StructuralEquals(leftEnum.Current, rightEnum.Current))
                    {
                        return false;
                    }
                }
            }
            finally
            {
                (leftEnum as IDisposable)?.Dispose();
                (rightEnum as IDisposable)?.Dispose();
            }
        }

        return left.Equals(right);
    }

    /// <summary>
    /// Content-based hash code matching <see cref="StructuralEquals"/>: equal
    /// values (including equal collections and byte arrays) hash identically.
    /// </summary>
    public static int StructuralHashCode(object? value)
    {
        if (value is null)
        {
            return 0;
        }

        if (value is byte[] bytes)
        {
            HashCode byteHash = default;
            byteHash.AddBytes(bytes);
            return byteHash.ToHashCode();
        }

        if (value is IDictionary dict)
        {
            /* Order-independent so two equal maps hash identically regardless of
               enumeration order. */
            int dictHash = 0;
            foreach (DictionaryEntry entry in dict)
            {
                dictHash ^= HashCode.Combine(
                    StructuralHashCode(entry.Key), StructuralHashCode(entry.Value));
            }

            return dictHash;
        }

        if (IsSet(value))
        {
            /* Order-independent so two equal sets hash identically regardless of
               enumeration order (HashSet<T> has no defined order). */
            int setHash = 0;
            foreach (object? item in (IEnumerable)value)
            {
                setHash ^= StructuralHashCode(item);
            }

            return setHash;
        }

        if (value is IEnumerable seq && value is not string)
        {
            HashCode seqHash = default;
            foreach (object? item in seq)
            {
                seqHash.Add(StructuralHashCode(item));
            }

            return seqHash.ToHashCode();
        }

        return value.GetHashCode();
    }

    /// <summary>
    /// True when <paramref name="value"/>'s runtime type implements
    /// <see cref="ISet{T}"/> (e.g. <c>HashSet{T}</c>). Sets have no
    /// defined enumeration order, so equality and hashing must be
    /// order-independent.
    /// </summary>
    private static bool IsSet(object value)
    {
        foreach (Type iface in value.GetType().GetInterfaces())
        {
            if (iface.IsGenericType
                && iface.GetGenericTypeDefinition() == typeof(ISet<>))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Order-independent structural equality for two sets: equal iff they have
    /// the same number of elements and every element of <paramref name="left"/>
    /// has a structurally-equal match in <paramref name="right"/> (matches are
    /// consumed so duplicates, were they possible, are handled correctly).
    /// </summary>
    private static bool SetStructuralEquals(IEnumerable left, IEnumerable right)
    {
        List<object?> remaining = new List<object?>();
        foreach (object? item in right)
        {
            remaining.Add(item);
        }

        foreach (object? leftItem in left)
        {
            int matchIndex = -1;
            for (int i = 0; i < remaining.Count; i++)
            {
                if (StructuralEquals(leftItem, remaining[i]))
                {
                    matchIndex = i;
                    break;
                }
            }

            /* No match means an element of left is absent from right, or left
               has more elements than right (right already exhausted). */
            if (matchIndex < 0)
            {
                return false;
            }

            remaining.RemoveAt(matchIndex);
        }

        /* Every left element consumed one right element; equal sizes iff no
           right elements are left over. */
        return remaining.Count == 0;
    }

}

/// <summary>
/// Serializes <see cref="TimeSpan"/> values as protobuf-JSON duration strings
/// (the canonical JSON mapping of <c>google.protobuf.Duration</c>) so that
/// <c>format:duration</c> schema values are accepted by protobuf/gRPC-gateway
/// backends. The wire form is a decimal number of seconds
/// suffixed with <c>s</c> — e.g. <c>"3600s"</c> or <c>"3600.000000001s"</c> —
/// NOT the ISO-8601 <c>PT1H</c> form (which such servers reject with 400).
///
/// .NET's default <c>TimeSpan</c> JSON form is <c>[d.]hh:mm:ss[.fff]</c>, which
/// is also rejected. Fractional seconds carry up to nanosecond precision;
/// because <see cref="TimeSpan"/> ticks are 100-ns, the smallest representable
/// fraction is <c>0.0000001s</c>. Negative durations carry a leading <c>-</c>.
/// </summary>
internal sealed partial class ProtobufDurationConverter : JsonConverter<TimeSpan>
{
    /* protobuf-JSON Duration: optional sign, integer seconds, optional
     * fractional part of 1..9 digits, mandatory 's' suffix. Anything else
     * (ISO-8601 "PT1H", a bare number, a trailing-dot form) is rejected.
     * [0-9], not \d: in .NET \d also matches non-ASCII digits. */
    [System.Text.RegularExpressions.GeneratedRegex(@"^-?[0-9]+(\.[0-9]{1,9})?s$")]
    private static partial System.Text.RegularExpressions.Regex DurationPattern();

    private const long TicksPerSecond = 10_000_000L;
    private const long NanosPerTick = 100L;

    public override TimeSpan Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? s = reader.GetString();
        if (string.IsNullOrEmpty(s))
        {
            throw new JsonException("protobuf duration string must not be empty");
        }
        return Parse(s);
    }

    public override void Write(Utf8JsonWriter writer, TimeSpan value, JsonSerializerOptions options)
    {
        ArgumentNullException.ThrowIfNull(writer);
        writer.WriteStringValue(Format(value));
    }

    /// <summary>
    /// Formats a <see cref="TimeSpan"/> as a protobuf-JSON duration string.
    /// Zero produces <c>0s</c>. A whole-second value produces <c>{secs}s</c>;
    /// a sub-second value produces <c>{secs}.{frac}s</c> with the fractional
    /// digits trimmed to 3, 6, or 9 places (the smallest grouping that keeps
    /// every non-zero digit), matching protobuf's canonical output.
    /// </summary>
    public static string Format(TimeSpan value)
    {
        string sign = value.Ticks < 0 ? "-" : "";
        long absTicks = Math.Abs(value.Ticks);
        long secs = absTicks / TicksPerSecond;
        long remainderTicks = absTicks % TicksPerSecond;
        long nanos = remainderTicks * NanosPerTick;
        if (nanos == 0L)
        {
            return $"{sign}{secs}s";
        }

        /* Zero-pad nanos to 9 digits, then trim to a 3/6/9-digit group so the
         * shortest representation that preserves every significant digit is
         * emitted (protobuf canonical form). */
        string frac = nanos.ToString("D9", System.Globalization.CultureInfo.InvariantCulture);
        int width = frac.EndsWith("000000", StringComparison.Ordinal)
            ? 3
            : frac.EndsWith("000", StringComparison.Ordinal) ? 6 : 9;
        frac = frac[..width];
        return $"{sign}{secs}.{frac}s";
    }

    /// <summary>
    /// Parses a protobuf-JSON duration string into a <see cref="TimeSpan"/>.
    /// Throws <see cref="JsonException"/> on anything not matching
    /// <c>^-?[0-9]+(\.[0-9]{1,9})?s$</c> (e.g. ISO-8601 or unsuffixed numbers)
    /// and on a value too large for <see cref="TimeSpan"/>;
    /// <see cref="ObjectSerializer"/> surfaces it as a
    /// <see cref="SerializationException"/>.
    /// </summary>
    public static TimeSpan Parse(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        if (!DurationPattern().IsMatch(text))
        {
            throw new JsonException($"Invalid protobuf duration: {text}");
        }

        bool negative = text[0] == '-';
        string body = text[..^1]; // strip trailing 's'
        if (negative)
        {
            body = body[1..];
        }

        int dot = body.IndexOf('.', StringComparison.Ordinal);
        string secsText = dot < 0 ? body : body[..dot];
        try
        {
            long secs = long.Parse(secsText, System.Globalization.CultureInfo.InvariantCulture);

            long nanos = 0L;
            if (dot >= 0)
            {
                /* Right-pad the fractional part to 9 digits so each position keeps
                 * its nanosecond weight (".5" → 500_000_000ns). */
                string fracText = body[(dot + 1)..].PadRight(9, '0');
                nanos = long.Parse(fracText, System.Globalization.CultureInfo.InvariantCulture);
            }

            /* checked: a second count past TimeSpan's range must fail, not wrap. */
            long ticks = checked((secs * TicksPerSecond) + (nanos / NanosPerTick));
            return TimeSpan.FromTicks(negative ? -ticks : ticks);
        }
        catch (Exception e) when (e is FormatException or OverflowException)
        {
            throw new JsonException($"Invalid protobuf duration: {text}", e);
        }
    }
}
