// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ActionServiceListPublicKeysRequest : IEquatable<ActionServiceListPublicKeysRequest>
{
    /// <summary>
    /// TargetID is the unique identifier of the target to list the public keys for.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("targetId")]
    public string? TargetId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public ActionServicePaginationRequest? Pagination { get; set; }

    /// <example>null</example>
    [JsonPropertyName("sortingColumn")]
    public ActionServicePublicKeyFieldName? SortingColumn { get; set; }

    /// <summary>
    /// Define the criteria to query for.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("filters")]
    public List<ActionServicePublicKeySearchFilter>? Filters { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ActionServiceListPublicKeysRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.TargetId, other.TargetId)
                    && EqualityComparer<ActionServicePaginationRequest?>.Default.Equals(this.Pagination, other.Pagination)
                    && EqualityComparer<ActionServicePublicKeyFieldName?>.Default.Equals(this.SortingColumn, other.SortingColumn)
                    && EqualityComparer<List<ActionServicePublicKeySearchFilter>?>.Default.Equals(this.Filters, other.Filters));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ActionServiceListPublicKeysRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.TargetId);
        hash.Add(this.Pagination);
        hash.Add(this.SortingColumn);
        hash.Add(this.Filters);
        return hash.ToHashCode();
    }
}
