// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ActionServiceInTargetIDsFilter : IEquatable<ActionServiceInTargetIDsFilter>
{
    /// <summary>
    /// Defines the ids to query for.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("targetIds")]
    public List<string>? TargetIds { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ActionServiceInTargetIDsFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<List<string>?>.Default.Equals(this.TargetIds, other.TargetIds));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ActionServiceInTargetIDsFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.TargetIds);
        return hash.ToHashCode();
    }
}
