// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ActionServiceEventExecution : IEquatable<ActionServiceEventExecution>
{
    /// <summary>
    /// Define all events as condition.  After any event is created, the execution is triggered.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("all")]
    public bool? All { get; set; }

    /// <summary>
    /// Define a specific event as condition.  After this event is created, the execution is triggered.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("event")]
    public string? _Event { get; set; }

    /// <summary>
    /// Define an event group as condition.  After any event under this group is created, the execution is triggered.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("group")]
    public string? Group { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ActionServiceEventExecution? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.All, other.All)
                    && EqualityComparer<string?>.Default.Equals(this._Event, other._Event)
                    && EqualityComparer<string?>.Default.Equals(this.Group, other.Group));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ActionServiceEventExecution);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.All);
        hash.Add(this._Event);
        hash.Add(this.Group);
        return hash.ToHashCode();
    }
}
