// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ActionServiceListExecutionsResponse : IEquatable<ActionServiceListExecutionsResponse>
{
    [JsonPropertyName("pagination")]
    public ActionServicePaginationResponse? Pagination { get; set; }

    /// <summary>
    /// List of all executions matching the query.
    /// </summary>
    [JsonPropertyName("executions")]
    public List<ActionServiceExecution>? Executions { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ActionServiceListExecutionsResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<ActionServicePaginationResponse?>.Default.Equals(
                    this.Pagination,
                    other.Pagination
                )
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(
                        this.Executions,
                        other.Executions
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ActionServiceListExecutionsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.Executions));
        return hash.ToHashCode();
    }
}
