// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

/// <summary>
/// Executed on the specified function
/// </summary>
public class ActionServiceFunctionExecution : IEquatable<ActionServiceFunctionExecution>
{
    /// <example>null</example>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ActionServiceFunctionExecution? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Name, other.Name)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ActionServiceFunctionExecution);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Name);
        return hash.ToHashCode();
    }
}
