// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceGetApplicationRequest
    : IEquatable<ApplicationServiceGetApplicationRequest>
{
    /// <summary>
    /// The unique ID of the application to be retrieved.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("applicationId")]
    public string? ApplicationId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceGetApplicationRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ApplicationId, other.ApplicationId)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceGetApplicationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ApplicationId);
        return hash.ToHashCode();
    }
}
