// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceListApplicationsResponse
    : IEquatable<ApplicationServiceListApplicationsResponse>
{
    /// <summary>
    /// The list of applications matching the query. Depending on the applied limit,  there might be more applications available than included in this list.  Use the returned pagination information to request further applications.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("applications")]
    public List<ApplicationServiceApplication>? Applications { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public ApplicationServicePaginationResponse? Pagination { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceListApplicationsResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<List<ApplicationServiceApplication>?>.Default.Equals(
                    this.Applications,
                    other.Applications
                )
                    && EqualityComparer<ApplicationServicePaginationResponse?>.Default.Equals(
                        this.Pagination,
                        other.Pagination
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceListApplicationsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Applications);
        hash.Add(this.Pagination);
        return hash.ToHashCode();
    }
}
