// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(ApplicationServiceAPIAuthMethodTypeConverter))]
public enum ApplicationServiceAPIAuthMethodType
{
    APIAUTHMETHODTYPEBASIC,

    APIAUTHMETHODTYPEPRIVATEKEYJWT,
}

/// <summary>
/// Serializes <see cref="ApplicationServiceAPIAuthMethodType"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class ApplicationServiceAPIAuthMethodTypeConverter
    : JsonConverter<ApplicationServiceAPIAuthMethodType>
{
    public override ApplicationServiceAPIAuthMethodType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException(
                $"Expected a JSON string for enum ApplicationServiceAPIAuthMethodType but got {reader.TokenType}."
            );
        }

        string? value = reader.GetString();
        return value switch
        {
            "API_AUTH_METHOD_TYPE_BASIC" =>
                ApplicationServiceAPIAuthMethodType.APIAUTHMETHODTYPEBASIC,
            "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT" =>
                ApplicationServiceAPIAuthMethodType.APIAUTHMETHODTYPEPRIVATEKEYJWT,
            _ => throw new JsonException(
                $"Unknown value '{value}' for enum ApplicationServiceAPIAuthMethodType."
            ),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ApplicationServiceAPIAuthMethodType value,
        JsonSerializerOptions options
    )
    {
        writer.WriteStringValue(
            value switch
            {
                ApplicationServiceAPIAuthMethodType.APIAUTHMETHODTYPEBASIC =>
                    "API_AUTH_METHOD_TYPE_BASIC",
                ApplicationServiceAPIAuthMethodType.APIAUTHMETHODTYPEPRIVATEKEYJWT =>
                    "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT",
                _ => throw new JsonException(
                    $"Unknown value '{value}' for enum ApplicationServiceAPIAuthMethodType."
                ),
            }
        );
    }
}
