// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceClientIDFilter : IEquatable<ApplicationServiceClientIDFilter>
{
    /// <summary>
    /// The clientID to search for. The search is performed as an exact match.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceClientIDFilter? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceClientIDFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ClientId);
        return hash.ToHashCode();
    }
}
