// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceListApplicationsRequest
    : IEquatable<ApplicationServiceListApplicationsRequest>
{
    [JsonPropertyName("pagination")]
    public ApplicationServicePaginationRequest? Pagination { get; set; }

    [JsonPropertyName("sortingColumn")]
    public ApplicationServiceApplicationSorting? SortingColumn { get; set; }

    /// <summary>
    /// Criteria to filter the applications.  All provided filters are combined with a logical AND.
    /// </summary>
    [JsonPropertyName("filters")]
    public List<ApplicationServiceApplicationSearchFilter>? Filters { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceListApplicationsRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<ApplicationServicePaginationRequest?>.Default.Equals(
                    this.Pagination,
                    other.Pagination
                )
                    && EqualityComparer<ApplicationServiceApplicationSorting?>.Default.Equals(
                        this.SortingColumn,
                        other.SortingColumn
                    )
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(
                        this.Filters,
                        other.Filters
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceListApplicationsRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(this.SortingColumn);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.Filters));
        return hash.ToHashCode();
    }
}
