// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceAPIConfiguration : IEquatable<ApplicationServiceAPIConfiguration>
{
    /// <summary>
    /// The unique OAuth2 client_id used for authentication of the API,  e.g. at the introspection endpoint.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("authMethodType")]
    public ApplicationServiceAPIAuthMethodType? AuthMethodType { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceAPIConfiguration? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
                    && EqualityComparer<ApplicationServiceAPIAuthMethodType?>.Default.Equals(this.AuthMethodType, other.AuthMethodType));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceAPIConfiguration);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ClientId);
        hash.Add(this.AuthMethodType);
        return hash.ToHashCode();
    }
}
