// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ApplicationServiceListApplicationKeysResponse
    : IEquatable<ApplicationServiceListApplicationKeysResponse>
{
    /// <summary>
    /// The list of application keys matching the query. Depending on the applied limit,  there might be more keys available than returned in this list.  Use the returned pagination information to request further keys.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("keys")]
    public List<ApplicationServiceApplicationKey>? Keys { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public ApplicationServicePaginationResponse? Pagination { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ApplicationServiceListApplicationKeysResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<List<ApplicationServiceApplicationKey>?>.Default.Equals(
                    this.Keys,
                    other.Keys
                )
                    && EqualityComparer<ApplicationServicePaginationResponse?>.Default.Equals(
                        this.Pagination,
                        other.Pagination
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ApplicationServiceListApplicationKeysResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Keys);
        hash.Add(this.Pagination);
        return hash.ToHashCode();
    }
}
