// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class AuthorizationServiceDeactivateAuthorizationRequest
    : IEquatable<AuthorizationServiceDeactivateAuthorizationRequest>
{
    /// <summary>
    /// ID is the unique identifier of the authorization that should be deactivated.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(AuthorizationServiceDeactivateAuthorizationRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Id, other.Id)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as AuthorizationServiceDeactivateAuthorizationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Id);
        return hash.ToHashCode();
    }
}
