// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class AuthorizationServiceProject : IEquatable<AuthorizationServiceProject>
{
    /// <summary>
    /// ID is the unique identifier of the project.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// Name is the name of the project.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// OrganizationID is the ID of the organization the project belongs to.  This does not have to correspond with the authorizations organization.  In case the authorization is given on a granted project, this is the organization  that owns the project and granted it.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(AuthorizationServiceProject? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Id, other.Id)
                    && EqualityComparer<string?>.Default.Equals(this.Name, other.Name)
                    && EqualityComparer<string?>.Default.Equals(this.OrganizationId, other.OrganizationId));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as AuthorizationServiceProject);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Id);
        hash.Add(this.Name);
        hash.Add(this.OrganizationId);
        return hash.ToHashCode();
    }
}
