// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class AuthorizationServiceProjectNameQuery : IEquatable<AuthorizationServiceProjectNameQuery>
{
    /// <summary>
    /// Specify the name of the project the user was granted the authorization for to search for.  Note that this will also include authorizations granted for project grants of the same project.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <example>null</example>
    [JsonPropertyName("method")]
    public AuthorizationServiceTextFilterMethod? Method { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(AuthorizationServiceProjectNameQuery? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Name, other.Name)
                    && EqualityComparer<AuthorizationServiceTextFilterMethod?>.Default.Equals(
                        this.Method,
                        other.Method
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as AuthorizationServiceProjectNameQuery);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Name);
        hash.Add(this.Method);
        return hash.ToHashCode();
    }
}
