// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(AuthorizationServiceAuthorizationFieldNameConverter))]
public enum AuthorizationServiceAuthorizationFieldName
{
    AUTHORIZATIONFIELDNAMEUNSPECIFIED,

    AUTHORIZATIONFIELDNAMECREATEDDATE,

    AUTHORIZATIONFIELDNAMECHANGEDDATE,

    AUTHORIZATIONFIELDNAMEID,

    AUTHORIZATIONFIELDNAMEUSERID,

    AUTHORIZATIONFIELDNAMEPROJECTID,

    AUTHORIZATIONFIELDNAMEORGANIZATIONID,

    AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID,
}

/// <summary>
/// Serializes <see cref="AuthorizationServiceAuthorizationFieldName"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class AuthorizationServiceAuthorizationFieldNameConverter : JsonConverter<AuthorizationServiceAuthorizationFieldName>
{
    public override AuthorizationServiceAuthorizationFieldName Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum AuthorizationServiceAuthorizationFieldName but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "AUTHORIZATION_FIELD_NAME_UNSPECIFIED" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUNSPECIFIED,
            "AUTHORIZATION_FIELD_NAME_CREATED_DATE" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECREATEDDATE,
            "AUTHORIZATION_FIELD_NAME_CHANGED_DATE" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECHANGEDDATE,
            "AUTHORIZATION_FIELD_NAME_ID" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEID,
            "AUTHORIZATION_FIELD_NAME_USER_ID" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERID,
            "AUTHORIZATION_FIELD_NAME_PROJECT_ID" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEPROJECTID,
            "AUTHORIZATION_FIELD_NAME_ORGANIZATION_ID" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEORGANIZATIONID,
            "AUTHORIZATION_FIELD_NAME_USER_ORGANIZATION_ID" => AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID,
            _ => throw new JsonException($"Unknown value '{value}' for enum AuthorizationServiceAuthorizationFieldName.")
        };
    }

    public override void Write(Utf8JsonWriter writer, AuthorizationServiceAuthorizationFieldName value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUNSPECIFIED => "AUTHORIZATION_FIELD_NAME_UNSPECIFIED",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECREATEDDATE => "AUTHORIZATION_FIELD_NAME_CREATED_DATE",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECHANGEDDATE => "AUTHORIZATION_FIELD_NAME_CHANGED_DATE",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEID => "AUTHORIZATION_FIELD_NAME_ID",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERID => "AUTHORIZATION_FIELD_NAME_USER_ID",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEPROJECTID => "AUTHORIZATION_FIELD_NAME_PROJECT_ID",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEORGANIZATIONID => "AUTHORIZATION_FIELD_NAME_ORGANIZATION_ID",
            AuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID => "AUTHORIZATION_FIELD_NAME_USER_ORGANIZATION_ID",
            _ => throw new JsonException($"Unknown value '{value}' for enum AuthorizationServiceAuthorizationFieldName.")
        });
    }
}
