// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaActionServiceRequestExecution : IEquatable<BetaActionServiceRequestExecution>
{
    /// <summary>
    /// All calls to any available services and methods as condition.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("all")]
    public bool? All { get; set; }

    /// <summary>
    /// GRPC-method as condition.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("method")]
    public string? Method { get; set; }

    /// <summary>
    /// GRPC-service as condition.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("service")]
    public string? Service { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaActionServiceRequestExecution? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.All, other.All)
                    && EqualityComparer<string?>.Default.Equals(this.Method, other.Method)
                    && EqualityComparer<string?>.Default.Equals(this.Service, other.Service)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaActionServiceRequestExecution);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.All);
        hash.Add(this.Method);
        hash.Add(this.Service);
        return hash.ToHashCode();
    }
}
