// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaOrganizationServiceTextQueryMethodConverter))]
public enum BetaOrganizationServiceTextQueryMethod
{
    TEXTQUERYMETHODEQUALS,

    TEXTQUERYMETHODEQUALSIGNORECASE,

    TEXTQUERYMETHODSTARTSWITH,

    TEXTQUERYMETHODSTARTSWITHIGNORECASE,

    TEXTQUERYMETHODCONTAINS,

    TEXTQUERYMETHODCONTAINSIGNORECASE,

    TEXTQUERYMETHODENDSWITH,

    TEXTQUERYMETHODENDSWITHIGNORECASE,
}

/// <summary>
/// Serializes <see cref="BetaOrganizationServiceTextQueryMethod"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaOrganizationServiceTextQueryMethodConverter
    : JsonConverter<BetaOrganizationServiceTextQueryMethod>
{
    public override BetaOrganizationServiceTextQueryMethod Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException(
                $"Expected a JSON string for enum BetaOrganizationServiceTextQueryMethod but got {reader.TokenType}."
            );
        }

        string? value = reader.GetString();
        return value switch
        {
            "TEXT_QUERY_METHOD_EQUALS" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALS,
            "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE,
            "TEXT_QUERY_METHOD_STARTS_WITH" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH,
            "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE,
            "TEXT_QUERY_METHOD_CONTAINS" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS,
            "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE,
            "TEXT_QUERY_METHOD_ENDS_WITH" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH,
            "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE" =>
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE,
            _ => throw new JsonException(
                $"Unknown value '{value}' for enum BetaOrganizationServiceTextQueryMethod."
            ),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        BetaOrganizationServiceTextQueryMethod value,
        JsonSerializerOptions options
    )
    {
        writer.WriteStringValue(
            value switch
            {
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALS =>
                    "TEXT_QUERY_METHOD_EQUALS",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE =>
                    "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH =>
                    "TEXT_QUERY_METHOD_STARTS_WITH",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE =>
                    "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS =>
                    "TEXT_QUERY_METHOD_CONTAINS",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE =>
                    "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH =>
                    "TEXT_QUERY_METHOD_ENDS_WITH",
                BetaOrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE =>
                    "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE",
                _ => throw new JsonException(
                    $"Unknown value '{value}' for enum BetaOrganizationServiceTextQueryMethod."
                ),
            }
        );
    }
}
