// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInternalPermissionServiceUserDisplayNameFilter
    : IEquatable<BetaInternalPermissionServiceUserDisplayNameFilter>
{
    /// <summary>
    /// Search for administrators by the display name of the user.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("displayName")]
    public string? DisplayName { get; set; }

    /// <example>null</example>
    [JsonPropertyName("method")]
    public BetaInternalPermissionServiceTextFilterMethod? Method { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInternalPermissionServiceUserDisplayNameFilter? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.DisplayName, other.DisplayName)
                    && EqualityComparer<BetaInternalPermissionServiceTextFilterMethod?>.Default.Equals(
                        this.Method,
                        other.Method
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInternalPermissionServiceUserDisplayNameFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.DisplayName);
        hash.Add(this.Method);
        return hash.ToHashCode();
    }
}
