// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaProjectServiceTextFilterMethodConverter))]
public enum BetaProjectServiceTextFilterMethod
{
    TEXTFILTERMETHODEQUALS,

    TEXTFILTERMETHODEQUALSIGNORECASE,

    TEXTFILTERMETHODSTARTSWITH,

    TEXTFILTERMETHODSTARTSWITHIGNORECASE,

    TEXTFILTERMETHODCONTAINS,

    TEXTFILTERMETHODCONTAINSIGNORECASE,

    TEXTFILTERMETHODENDSWITH,

    TEXTFILTERMETHODENDSWITHIGNORECASE,
}

/// <summary>
/// Serializes <see cref="BetaProjectServiceTextFilterMethod"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaProjectServiceTextFilterMethodConverter : JsonConverter<BetaProjectServiceTextFilterMethod>
{
    public override BetaProjectServiceTextFilterMethod Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaProjectServiceTextFilterMethod but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "TEXT_FILTER_METHOD_EQUALS" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODEQUALS,
            "TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODEQUALSIGNORECASE,
            "TEXT_FILTER_METHOD_STARTS_WITH" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODSTARTSWITH,
            "TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODSTARTSWITHIGNORECASE,
            "TEXT_FILTER_METHOD_CONTAINS" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODCONTAINS,
            "TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODCONTAINSIGNORECASE,
            "TEXT_FILTER_METHOD_ENDS_WITH" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODENDSWITH,
            "TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE" => BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODENDSWITHIGNORECASE,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaProjectServiceTextFilterMethod.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaProjectServiceTextFilterMethod value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODEQUALS => "TEXT_FILTER_METHOD_EQUALS",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODEQUALSIGNORECASE => "TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODSTARTSWITH => "TEXT_FILTER_METHOD_STARTS_WITH",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODSTARTSWITHIGNORECASE => "TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODCONTAINS => "TEXT_FILTER_METHOD_CONTAINS",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODCONTAINSIGNORECASE => "TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODENDSWITH => "TEXT_FILTER_METHOD_ENDS_WITH",
            BetaProjectServiceTextFilterMethod.TEXTFILTERMETHODENDSWITHIGNORECASE => "TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaProjectServiceTextFilterMethod.")
        });
    }
}
