// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaAppServiceCreateSAMLApplicationRequest : IEquatable<BetaAppServiceCreateSAMLApplicationRequest>
{
    /// <example>null</example>
    [JsonPropertyName("loginVersion")]
    public BetaAppServiceLoginVersion? LoginVersion { get; set; }

    /// <example>null</example>
    [JsonPropertyName("metadataUrl")]
    public string? MetadataUrl { get; set; }

    /// <example>null</example>
    [JsonPropertyName("metadataXml")]
    public byte[]? MetadataXml { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaAppServiceCreateSAMLApplicationRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaAppServiceLoginVersion?>.Default.Equals(this.LoginVersion, other.LoginVersion)
                    && EqualityComparer<string?>.Default.Equals(this.MetadataUrl, other.MetadataUrl)
                    && EqualityComparer<byte[]?>.Default.Equals(this.MetadataXml, other.MetadataXml));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaAppServiceCreateSAMLApplicationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.LoginVersion);
        hash.Add(this.MetadataUrl);
        hash.Add(this.MetadataXml);
        return hash.ToHashCode();
    }
}
