// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaAuthorizationServiceAuthorizationFieldNameConverter))]
public enum BetaAuthorizationServiceAuthorizationFieldName
{
    AUTHORIZATIONFIELDNAMEUNSPECIFIED,

    AUTHORIZATIONFIELDNAMECREATEDDATE,

    AUTHORIZATIONFIELDNAMECHANGEDDATE,

    AUTHORIZATIONFIELDNAMEID,

    AUTHORIZATIONFIELDNAMEUSERID,

    AUTHORIZATIONFIELDNAMEPROJECTID,

    AUTHORIZATIONFIELDNAMEORGANIZATIONID,

    AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID,
}

/// <summary>
/// Serializes <see cref="BetaAuthorizationServiceAuthorizationFieldName"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaAuthorizationServiceAuthorizationFieldNameConverter : JsonConverter<BetaAuthorizationServiceAuthorizationFieldName>
{
    public override BetaAuthorizationServiceAuthorizationFieldName Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaAuthorizationServiceAuthorizationFieldName but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "AUTHORIZATION_FIELD_NAME_UNSPECIFIED" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUNSPECIFIED,
            "AUTHORIZATION_FIELD_NAME_CREATED_DATE" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECREATEDDATE,
            "AUTHORIZATION_FIELD_NAME_CHANGED_DATE" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECHANGEDDATE,
            "AUTHORIZATION_FIELD_NAME_ID" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEID,
            "AUTHORIZATION_FIELD_NAME_USER_ID" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERID,
            "AUTHORIZATION_FIELD_NAME_PROJECT_ID" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEPROJECTID,
            "AUTHORIZATION_FIELD_NAME_ORGANIZATION_ID" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEORGANIZATIONID,
            "AUTHORIZATION_FIELD_NAME_USER_ORGANIZATION_ID" => BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaAuthorizationServiceAuthorizationFieldName.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaAuthorizationServiceAuthorizationFieldName value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUNSPECIFIED => "AUTHORIZATION_FIELD_NAME_UNSPECIFIED",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECREATEDDATE => "AUTHORIZATION_FIELD_NAME_CREATED_DATE",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMECHANGEDDATE => "AUTHORIZATION_FIELD_NAME_CHANGED_DATE",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEID => "AUTHORIZATION_FIELD_NAME_ID",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERID => "AUTHORIZATION_FIELD_NAME_USER_ID",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEPROJECTID => "AUTHORIZATION_FIELD_NAME_PROJECT_ID",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEORGANIZATIONID => "AUTHORIZATION_FIELD_NAME_ORGANIZATION_ID",
            BetaAuthorizationServiceAuthorizationFieldName.AUTHORIZATIONFIELDNAMEUSERORGANIZATIONID => "AUTHORIZATION_FIELD_NAME_USER_ORGANIZATION_ID",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaAuthorizationServiceAuthorizationFieldName.")
        });
    }
}
