// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaTelemetryServiceReportResourceCountsResponse : IEquatable<BetaTelemetryServiceReportResourceCountsResponse>
{
    /// <summary>
    /// The report ID is a unique identifier for the report.  It is used to identify the report in case of additional data / pagination.  Note that the report ID is only valid for the same system ID.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("reportId")]
    public string? ReportId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaTelemetryServiceReportResourceCountsResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ReportId, other.ReportId));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaTelemetryServiceReportResourceCountsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ReportId);
        return hash.ToHashCode();
    }
}
