// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceSearchQuery : IEquatable<BetaUserServiceSearchQuery>
{
    /// <example>null</example>
    [JsonPropertyName("andQuery")]
    public BetaUserServiceAndQuery? AndQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("displayNameQuery")]
    public BetaUserServiceDisplayNameQuery? DisplayNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("emailQuery")]
    public BetaUserServiceEmailQuery? EmailQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("firstNameQuery")]
    public BetaUserServiceFirstNameQuery? FirstNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("inUserEmailsQuery")]
    public BetaUserServiceInUserEmailsQuery? InUserEmailsQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("inUserIdsQuery")]
    public BetaUserServiceInUserIDQuery? InUserIdsQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("lastNameQuery")]
    public BetaUserServiceLastNameQuery? LastNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("loginNameQuery")]
    public BetaUserServiceLoginNameQuery? LoginNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("nickNameQuery")]
    public BetaUserServiceNickNameQuery? NickNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("notQuery")]
    public BetaUserServiceNotQuery? NotQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("orQuery")]
    public BetaUserServiceOrQuery? OrQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("organizationIdQuery")]
    public BetaUserServiceOrganizationIdQuery? OrganizationIdQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("phoneQuery")]
    public BetaUserServicePhoneQuery? PhoneQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("stateQuery")]
    public BetaUserServiceStateQuery? StateQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("typeQuery")]
    public BetaUserServiceTypeQuery? TypeQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userNameQuery")]
    public BetaUserServiceUserNameQuery? UserNameQuery { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceSearchQuery? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaUserServiceAndQuery?>.Default.Equals(this.AndQuery, other.AndQuery)
                    && EqualityComparer<BetaUserServiceDisplayNameQuery?>.Default.Equals(this.DisplayNameQuery, other.DisplayNameQuery)
                    && EqualityComparer<BetaUserServiceEmailQuery?>.Default.Equals(this.EmailQuery, other.EmailQuery)
                    && EqualityComparer<BetaUserServiceFirstNameQuery?>.Default.Equals(this.FirstNameQuery, other.FirstNameQuery)
                    && EqualityComparer<BetaUserServiceInUserEmailsQuery?>.Default.Equals(this.InUserEmailsQuery, other.InUserEmailsQuery)
                    && EqualityComparer<BetaUserServiceInUserIDQuery?>.Default.Equals(this.InUserIdsQuery, other.InUserIdsQuery)
                    && EqualityComparer<BetaUserServiceLastNameQuery?>.Default.Equals(this.LastNameQuery, other.LastNameQuery)
                    && EqualityComparer<BetaUserServiceLoginNameQuery?>.Default.Equals(this.LoginNameQuery, other.LoginNameQuery)
                    && EqualityComparer<BetaUserServiceNickNameQuery?>.Default.Equals(this.NickNameQuery, other.NickNameQuery)
                    && EqualityComparer<BetaUserServiceNotQuery?>.Default.Equals(this.NotQuery, other.NotQuery)
                    && EqualityComparer<BetaUserServiceOrQuery?>.Default.Equals(this.OrQuery, other.OrQuery)
                    && EqualityComparer<BetaUserServiceOrganizationIdQuery?>.Default.Equals(this.OrganizationIdQuery, other.OrganizationIdQuery)
                    && EqualityComparer<BetaUserServicePhoneQuery?>.Default.Equals(this.PhoneQuery, other.PhoneQuery)
                    && EqualityComparer<BetaUserServiceStateQuery?>.Default.Equals(this.StateQuery, other.StateQuery)
                    && EqualityComparer<BetaUserServiceTypeQuery?>.Default.Equals(this.TypeQuery, other.TypeQuery)
                    && EqualityComparer<BetaUserServiceUserNameQuery?>.Default.Equals(this.UserNameQuery, other.UserNameQuery));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceSearchQuery);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.AndQuery);
        hash.Add(this.DisplayNameQuery);
        hash.Add(this.EmailQuery);
        hash.Add(this.FirstNameQuery);
        hash.Add(this.InUserEmailsQuery);
        hash.Add(this.InUserIdsQuery);
        hash.Add(this.LastNameQuery);
        hash.Add(this.LoginNameQuery);
        hash.Add(this.NickNameQuery);
        hash.Add(this.NotQuery);
        hash.Add(this.OrQuery);
        hash.Add(this.OrganizationIdQuery);
        hash.Add(this.PhoneQuery);
        hash.Add(this.StateQuery);
        hash.Add(this.TypeQuery);
        hash.Add(this.UserNameQuery);
        return hash.ToHashCode();
    }
}
