// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInternalPermissionServiceUserPreferredLoginNameFilter : IEquatable<BetaInternalPermissionServiceUserPreferredLoginNameFilter>
{
    /// <summary>
    /// Search for administrators by the preferred login name of the user.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("preferredLoginName")]
    public string? PreferredLoginName { get; set; }

    /// <example>null</example>
    [JsonPropertyName("method")]
    public BetaInternalPermissionServiceTextFilterMethod? Method { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInternalPermissionServiceUserPreferredLoginNameFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.PreferredLoginName, other.PreferredLoginName)
                    && EqualityComparer<BetaInternalPermissionServiceTextFilterMethod?>.Default.Equals(this.Method, other.Method));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInternalPermissionServiceUserPreferredLoginNameFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.PreferredLoginName);
        hash.Add(this.Method);
        return hash.ToHashCode();
    }
}
