// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceHashedPassword : IEquatable<BetaUserServiceHashedPassword>
{
    /// <example>null</example>
    [JsonPropertyName("hash")]
    public string? Hash { get; set; }

    /// <example>null</example>
    [JsonPropertyName("changeRequired")]
    public bool? ChangeRequired { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceHashedPassword? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Hash, other.Hash)
                    && EqualityComparer<bool?>.Default.Equals(this.ChangeRequired, other.ChangeRequired));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceHashedPassword);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Hash);
        hash.Add(this.ChangeRequired);
        return hash.ToHashCode();
    }
}
