// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaActionServiceInConditionsFilter : IEquatable<BetaActionServiceInConditionsFilter>
{
    /// <summary>
    /// Defines the conditions to query for.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("conditions")]
    public List<BetaActionServiceCondition>? Conditions { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaActionServiceInConditionsFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<List<BetaActionServiceCondition>?>.Default.Equals(this.Conditions, other.Conditions));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaActionServiceInConditionsFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Conditions);
        return hash.ToHashCode();
    }
}
