// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInstanceServiceListInstancesResponse
    : IEquatable<BetaInstanceServiceListInstancesResponse>
{
    /// <summary>
    /// The list of instances.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instances")]
    public List<BetaInstanceServiceInstance>? Instances { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public BetaInstanceServicePaginationResponse? Pagination { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInstanceServiceListInstancesResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<List<BetaInstanceServiceInstance>?>.Default.Equals(
                    this.Instances,
                    other.Instances
                )
                    && EqualityComparer<BetaInstanceServicePaginationResponse?>.Default.Equals(
                        this.Pagination,
                        other.Pagination
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInstanceServiceListInstancesResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Instances);
        hash.Add(this.Pagination);
        return hash.ToHashCode();
    }
}
