// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaActionServiceExecutionFieldNameConverter))]
public enum BetaActionServiceExecutionFieldName
{
    EXECUTIONFIELDNAMEUNSPECIFIED,

    EXECUTIONFIELDNAMEID,

    EXECUTIONFIELDNAMECREATEDDATE,

    EXECUTIONFIELDNAMECHANGEDDATE,
}

/// <summary>
/// Serializes <see cref="BetaActionServiceExecutionFieldName"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaActionServiceExecutionFieldNameConverter : JsonConverter<BetaActionServiceExecutionFieldName>
{
    public override BetaActionServiceExecutionFieldName Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaActionServiceExecutionFieldName but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "EXECUTION_FIELD_NAME_UNSPECIFIED" => BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMEUNSPECIFIED,
            "EXECUTION_FIELD_NAME_ID" => BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMEID,
            "EXECUTION_FIELD_NAME_CREATED_DATE" => BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMECREATEDDATE,
            "EXECUTION_FIELD_NAME_CHANGED_DATE" => BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMECHANGEDDATE,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaActionServiceExecutionFieldName.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaActionServiceExecutionFieldName value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMEUNSPECIFIED => "EXECUTION_FIELD_NAME_UNSPECIFIED",
            BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMEID => "EXECUTION_FIELD_NAME_ID",
            BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMECREATEDDATE => "EXECUTION_FIELD_NAME_CREATED_DATE",
            BetaActionServiceExecutionFieldName.EXECUTIONFIELDNAMECHANGEDDATE => "EXECUTION_FIELD_NAME_CHANGED_DATE",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaActionServiceExecutionFieldName.")
        });
    }
}
