// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceVerifyPasskeyRegistrationRequest : IEquatable<BetaUserServiceVerifyPasskeyRegistrationRequest>
{
    [JsonPropertyName("userId")]
    public string? UserId { get; set; }

    [JsonPropertyName("passkeyId")]
    public string? PasskeyId { get; set; }

    /// <summary>
    /// `Struct` represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, `Struct`  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for `Struct` is JSON object.
    /// </summary>
    [JsonPropertyName("publicKeyCredential")]
    public Dictionary<string, object>? PublicKeyCredential { get; set; }

    [JsonPropertyName("passkeyName")]
    public string? PasskeyName { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceVerifyPasskeyRegistrationRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.UserId, other.UserId)
                    && EqualityComparer<string?>.Default.Equals(this.PasskeyId, other.PasskeyId)
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(this.PublicKeyCredential, other.PublicKeyCredential)
                    && EqualityComparer<string?>.Default.Equals(this.PasskeyName, other.PasskeyName));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceVerifyPasskeyRegistrationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.UserId);
        hash.Add(this.PasskeyId);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.PublicKeyCredential));
        hash.Add(this.PasskeyName);
        return hash.ToHashCode();
    }
}
