// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

/// <summary>
/// The Admin for the newly created Organization.
/// </summary>
public class BetaOrganizationServiceAdmin : IEquatable<BetaOrganizationServiceAdmin>
{
    /// <summary>
    /// specify Organization Member Roles for the provided user (default is ORG_OWNER if roles are empty)
    /// </summary>
    [JsonPropertyName("roles")]
    public List<string>? Roles { get; set; }

    [JsonPropertyName("human")]
    public BetaOrganizationServiceAddHumanUserRequest? Human { get; set; }

    [JsonPropertyName("userId")]
    public string? UserId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaOrganizationServiceAdmin? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || global::Zitadel.Client.ObjectSerializer.StructuralEquals(this.Roles, other.Roles)
                    && EqualityComparer<BetaOrganizationServiceAddHumanUserRequest?>.Default.Equals(this.Human, other.Human)
                    && EqualityComparer<string?>.Default.Equals(this.UserId, other.UserId));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaOrganizationServiceAdmin);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.Roles));
        hash.Add(this.Human);
        hash.Add(this.UserId);
        return hash.ToHashCode();
    }
}
