// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceDeleteUserRequest : IEquatable<BetaUserServiceDeleteUserRequest>
{
    /// <example>null</example>
    [JsonPropertyName("userId")]
    public string? UserId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceDeleteUserRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.UserId, other.UserId)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceDeleteUserRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.UserId);
        return hash.ToHashCode();
    }
}
