// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaUserServiceAuthenticationMethodTypeConverter))]
public enum BetaUserServiceAuthenticationMethodType
{
    AUTHENTICATIONMETHODTYPEUNSPECIFIED,

    AUTHENTICATIONMETHODTYPEPASSWORD,

    AUTHENTICATIONMETHODTYPEPASSKEY,

    AUTHENTICATIONMETHODTYPEIDP,

    AUTHENTICATIONMETHODTYPETOTP,

    AUTHENTICATIONMETHODTYPEU2F,

    AUTHENTICATIONMETHODTYPEOTPSMS,

    AUTHENTICATIONMETHODTYPEOTPEMAIL,
}

/// <summary>
/// Serializes <see cref="BetaUserServiceAuthenticationMethodType"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaUserServiceAuthenticationMethodTypeConverter
    : JsonConverter<BetaUserServiceAuthenticationMethodType>
{
    public override BetaUserServiceAuthenticationMethodType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException(
                $"Expected a JSON string for enum BetaUserServiceAuthenticationMethodType but got {reader.TokenType}."
            );
        }

        string? value = reader.GetString();
        return value switch
        {
            "AUTHENTICATION_METHOD_TYPE_UNSPECIFIED" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEUNSPECIFIED,
            "AUTHENTICATION_METHOD_TYPE_PASSWORD" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEPASSWORD,
            "AUTHENTICATION_METHOD_TYPE_PASSKEY" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEPASSKEY,
            "AUTHENTICATION_METHOD_TYPE_IDP" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEIDP,
            "AUTHENTICATION_METHOD_TYPE_TOTP" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPETOTP,
            "AUTHENTICATION_METHOD_TYPE_U2F" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEU2F,
            "AUTHENTICATION_METHOD_TYPE_OTP_SMS" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEOTPSMS,
            "AUTHENTICATION_METHOD_TYPE_OTP_EMAIL" =>
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEOTPEMAIL,
            _ => throw new JsonException(
                $"Unknown value '{value}' for enum BetaUserServiceAuthenticationMethodType."
            ),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        BetaUserServiceAuthenticationMethodType value,
        JsonSerializerOptions options
    )
    {
        writer.WriteStringValue(
            value switch
            {
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEUNSPECIFIED =>
                    "AUTHENTICATION_METHOD_TYPE_UNSPECIFIED",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEPASSWORD =>
                    "AUTHENTICATION_METHOD_TYPE_PASSWORD",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEPASSKEY =>
                    "AUTHENTICATION_METHOD_TYPE_PASSKEY",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEIDP =>
                    "AUTHENTICATION_METHOD_TYPE_IDP",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPETOTP =>
                    "AUTHENTICATION_METHOD_TYPE_TOTP",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEU2F =>
                    "AUTHENTICATION_METHOD_TYPE_U2F",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEOTPSMS =>
                    "AUTHENTICATION_METHOD_TYPE_OTP_SMS",
                BetaUserServiceAuthenticationMethodType.AUTHENTICATIONMETHODTYPEOTPEMAIL =>
                    "AUTHENTICATION_METHOD_TYPE_OTP_EMAIL",
                _ => throw new JsonException(
                    $"Unknown value '{value}' for enum BetaUserServiceAuthenticationMethodType."
                ),
            }
        );
    }
}
