// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInternalPermissionServiceOrFilter
    : IEquatable<BetaInternalPermissionServiceOrFilter>
{
    /// <example>null</example>
    [JsonPropertyName("queries")]
    public List<BetaInternalPermissionServiceAdministratorSearchFilter>? Queries { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInternalPermissionServiceOrFilter? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<List<BetaInternalPermissionServiceAdministratorSearchFilter>?>.Default.Equals(
                    this.Queries,
                    other.Queries
                )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInternalPermissionServiceOrFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Queries);
        return hash.ToHashCode();
    }
}
