// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaSettingsServiceSecondFactorTypeConverter))]
public enum BetaSettingsServiceSecondFactorType
{
    SECONDFACTORTYPEUNSPECIFIED,

    SECONDFACTORTYPEOTP,

    SECONDFACTORTYPEU2F,

    SECONDFACTORTYPEOTPEMAIL,

    SECONDFACTORTYPEOTPSMS,
}

/// <summary>
/// Serializes <see cref="BetaSettingsServiceSecondFactorType"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaSettingsServiceSecondFactorTypeConverter : JsonConverter<BetaSettingsServiceSecondFactorType>
{
    public override BetaSettingsServiceSecondFactorType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaSettingsServiceSecondFactorType but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "SECOND_FACTOR_TYPE_UNSPECIFIED" => BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEUNSPECIFIED,
            "SECOND_FACTOR_TYPE_OTP" => BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTP,
            "SECOND_FACTOR_TYPE_U2F" => BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEU2F,
            "SECOND_FACTOR_TYPE_OTP_EMAIL" => BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTPEMAIL,
            "SECOND_FACTOR_TYPE_OTP_SMS" => BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTPSMS,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaSettingsServiceSecondFactorType.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaSettingsServiceSecondFactorType value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEUNSPECIFIED => "SECOND_FACTOR_TYPE_UNSPECIFIED",
            BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTP => "SECOND_FACTOR_TYPE_OTP",
            BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEU2F => "SECOND_FACTOR_TYPE_U2F",
            BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTPEMAIL => "SECOND_FACTOR_TYPE_OTP_EMAIL",
            BetaSettingsServiceSecondFactorType.SECONDFACTORTYPEOTPSMS => "SECOND_FACTOR_TYPE_OTP_SMS",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaSettingsServiceSecondFactorType.")
        });
    }
}
