// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum BetaUserServiceUserFieldName
{
    [JsonStringEnumMemberName("USER_FIELD_NAME_UNSPECIFIED")]
    USERFIELDNAMEUNSPECIFIED,

    [JsonStringEnumMemberName("USER_FIELD_NAME_USER_NAME")]
    USERFIELDNAMEUSERNAME,

    [JsonStringEnumMemberName("USER_FIELD_NAME_FIRST_NAME")]
    USERFIELDNAMEFIRSTNAME,

    [JsonStringEnumMemberName("USER_FIELD_NAME_LAST_NAME")]
    USERFIELDNAMELASTNAME,

    [JsonStringEnumMemberName("USER_FIELD_NAME_NICK_NAME")]
    USERFIELDNAMENICKNAME,

    [JsonStringEnumMemberName("USER_FIELD_NAME_DISPLAY_NAME")]
    USERFIELDNAMEDISPLAYNAME,

    [JsonStringEnumMemberName("USER_FIELD_NAME_EMAIL")]
    USERFIELDNAMEEMAIL,

    [JsonStringEnumMemberName("USER_FIELD_NAME_STATE")]
    USERFIELDNAMESTATE,

    [JsonStringEnumMemberName("USER_FIELD_NAME_TYPE")]
    USERFIELDNAMETYPE,

    [JsonStringEnumMemberName("USER_FIELD_NAME_CREATION_DATE")]
    USERFIELDNAMECREATIONDATE,
}
