// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaAppServiceOIDCLocalizedMessage : IEquatable<BetaAppServiceOIDCLocalizedMessage>
{
    /// <example>null</example>
    [JsonPropertyName("key")]
    public string? Key { get; set; }

    /// <example>null</example>
    [JsonPropertyName("localizedMessage")]
    public string? LocalizedMessage { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaAppServiceOIDCLocalizedMessage? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Key, other.Key)
                    && EqualityComparer<string?>.Default.Equals(this.LocalizedMessage, other.LocalizedMessage));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaAppServiceOIDCLocalizedMessage);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Key);
        hash.Add(this.LocalizedMessage);
        return hash.ToHashCode();
    }
}
