// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

/// <summary>
/// Query for users with a specific nickname.
/// </summary>
public class BetaUserServiceNickNameQuery : IEquatable<BetaUserServiceNickNameQuery>
{
    /// <example>null</example>
    [JsonPropertyName("nickName")]
    public string? NickName { get; set; }

    /// <example>null</example>
    [JsonPropertyName("method")]
    public BetaUserServiceTextQueryMethod? Method { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceNickNameQuery? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.NickName, other.NickName)
                    && EqualityComparer<BetaUserServiceTextQueryMethod?>.Default.Equals(
                        this.Method,
                        other.Method
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceNickNameQuery);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.NickName);
        hash.Add(this.Method);
        return hash.ToHashCode();
    }
}
