// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaSessionServiceWebAuthN : IEquatable<BetaSessionServiceWebAuthN>
{
    /// <example>null</example>
    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userVerificationRequirement")]
    public BetaSessionServiceUserVerificationRequirement? UserVerificationRequirement { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaSessionServiceWebAuthN? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Domain, other.Domain)
                    && EqualityComparer<BetaSessionServiceUserVerificationRequirement?>.Default.Equals(
                        this.UserVerificationRequirement,
                        other.UserVerificationRequirement
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaSessionServiceWebAuthN);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Domain);
        hash.Add(this.UserVerificationRequirement);
        return hash.ToHashCode();
    }
}
