// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaOrganizationServiceOrganizationSearchFilter : IEquatable<BetaOrganizationServiceOrganizationSearchFilter>
{
    /// <example>null</example>
    [JsonPropertyName("domainFilter")]
    public BetaOrganizationServiceOrgDomainFilter? DomainFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("idFilter")]
    public BetaOrganizationServiceOrgIDFilter? IdFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("nameFilter")]
    public BetaOrganizationServiceOrgNameFilter? NameFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("stateFilter")]
    public BetaOrganizationServiceOrgStateFilter? StateFilter { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaOrganizationServiceOrganizationSearchFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaOrganizationServiceOrgDomainFilter?>.Default.Equals(this.DomainFilter, other.DomainFilter)
                    && EqualityComparer<BetaOrganizationServiceOrgIDFilter?>.Default.Equals(this.IdFilter, other.IdFilter)
                    && EqualityComparer<BetaOrganizationServiceOrgNameFilter?>.Default.Equals(this.NameFilter, other.NameFilter)
                    && EqualityComparer<BetaOrganizationServiceOrgStateFilter?>.Default.Equals(this.StateFilter, other.StateFilter));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaOrganizationServiceOrganizationSearchFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.DomainFilter);
        hash.Add(this.IdFilter);
        hash.Add(this.NameFilter);
        hash.Add(this.StateFilter);
        return hash.ToHashCode();
    }
}
