// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInstanceServiceListCustomDomainsRequest : IEquatable<BetaInstanceServiceListCustomDomainsRequest>
{
    /// <example>null</example>
    [JsonPropertyName("instanceId")]
    public string? InstanceId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public BetaInstanceServicePaginationRequest? Pagination { get; set; }

    /// <example>null</example>
    [JsonPropertyName("sortingColumn")]
    public BetaInstanceServiceDomainFieldName? SortingColumn { get; set; }

    /// <summary>
    /// Criterias the client is looking for.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("queries")]
    public List<BetaInstanceServiceDomainSearchQuery>? Queries { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInstanceServiceListCustomDomainsRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.InstanceId, other.InstanceId)
                    && EqualityComparer<BetaInstanceServicePaginationRequest?>.Default.Equals(this.Pagination, other.Pagination)
                    && EqualityComparer<BetaInstanceServiceDomainFieldName?>.Default.Equals(this.SortingColumn, other.SortingColumn)
                    && EqualityComparer<List<BetaInstanceServiceDomainSearchQuery>?>.Default.Equals(this.Queries, other.Queries));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInstanceServiceListCustomDomainsRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.InstanceId);
        hash.Add(this.Pagination);
        hash.Add(this.SortingColumn);
        hash.Add(this.Queries);
        return hash.ToHashCode();
    }
}
