// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaProjectServiceUpdateProjectGrantRequest : IEquatable<BetaProjectServiceUpdateProjectGrantRequest>
{
    /// <summary>
    /// ID of the project.
    /// </summary>
    [JsonPropertyName("projectId")]
    public string? ProjectId { get; set; }

    /// <summary>
    /// Organization the project is granted to.
    /// </summary>
    [JsonPropertyName("grantedOrganizationId")]
    public string? GrantedOrganizationId { get; set; }

    /// <summary>
    /// Keys of the role available for the project grant.
    /// </summary>
    [JsonPropertyName("roleKeys")]
    public List<string>? RoleKeys { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaProjectServiceUpdateProjectGrantRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ProjectId, other.ProjectId)
                    && EqualityComparer<string?>.Default.Equals(this.GrantedOrganizationId, other.GrantedOrganizationId)
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(this.RoleKeys, other.RoleKeys));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaProjectServiceUpdateProjectGrantRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ProjectId);
        hash.Add(this.GrantedOrganizationId);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.RoleKeys));
        return hash.ToHashCode();
    }
}
