// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaActionServiceTargetFieldNameConverter))]
public enum BetaActionServiceTargetFieldName
{
    TARGETFIELDNAMEUNSPECIFIED,

    TARGETFIELDNAMEID,

    TARGETFIELDNAMECREATEDDATE,

    TARGETFIELDNAMECHANGEDDATE,

    TARGETFIELDNAMENAME,

    TARGETFIELDNAMETARGETTYPE,

    TARGETFIELDNAMEURL,

    TARGETFIELDNAMETIMEOUT,

    TARGETFIELDNAMEINTERRUPTONERROR,
}

/// <summary>
/// Serializes <see cref="BetaActionServiceTargetFieldName"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaActionServiceTargetFieldNameConverter : JsonConverter<BetaActionServiceTargetFieldName>
{
    public override BetaActionServiceTargetFieldName Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaActionServiceTargetFieldName but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "TARGET_FIELD_NAME_UNSPECIFIED" => BetaActionServiceTargetFieldName.TARGETFIELDNAMEUNSPECIFIED,
            "TARGET_FIELD_NAME_ID" => BetaActionServiceTargetFieldName.TARGETFIELDNAMEID,
            "TARGET_FIELD_NAME_CREATED_DATE" => BetaActionServiceTargetFieldName.TARGETFIELDNAMECREATEDDATE,
            "TARGET_FIELD_NAME_CHANGED_DATE" => BetaActionServiceTargetFieldName.TARGETFIELDNAMECHANGEDDATE,
            "TARGET_FIELD_NAME_NAME" => BetaActionServiceTargetFieldName.TARGETFIELDNAMENAME,
            "TARGET_FIELD_NAME_TARGET_TYPE" => BetaActionServiceTargetFieldName.TARGETFIELDNAMETARGETTYPE,
            "TARGET_FIELD_NAME_URL" => BetaActionServiceTargetFieldName.TARGETFIELDNAMEURL,
            "TARGET_FIELD_NAME_TIMEOUT" => BetaActionServiceTargetFieldName.TARGETFIELDNAMETIMEOUT,
            "TARGET_FIELD_NAME_INTERRUPT_ON_ERROR" => BetaActionServiceTargetFieldName.TARGETFIELDNAMEINTERRUPTONERROR,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaActionServiceTargetFieldName.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaActionServiceTargetFieldName value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaActionServiceTargetFieldName.TARGETFIELDNAMEUNSPECIFIED => "TARGET_FIELD_NAME_UNSPECIFIED",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMEID => "TARGET_FIELD_NAME_ID",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMECREATEDDATE => "TARGET_FIELD_NAME_CREATED_DATE",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMECHANGEDDATE => "TARGET_FIELD_NAME_CHANGED_DATE",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMENAME => "TARGET_FIELD_NAME_NAME",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMETARGETTYPE => "TARGET_FIELD_NAME_TARGET_TYPE",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMEURL => "TARGET_FIELD_NAME_URL",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMETIMEOUT => "TARGET_FIELD_NAME_TIMEOUT",
            BetaActionServiceTargetFieldName.TARGETFIELDNAMEINTERRUPTONERROR => "TARGET_FIELD_NAME_INTERRUPT_ON_ERROR",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaActionServiceTargetFieldName.")
        });
    }
}
