// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaOrganizationServiceDeleteOrganizationDomainRequest : IEquatable<BetaOrganizationServiceDeleteOrganizationDomainRequest>
{
    /// <summary>
    /// Organization Id for the Organization which domain is to be deleted.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaOrganizationServiceDeleteOrganizationDomainRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.OrganizationId, other.OrganizationId)
                    && EqualityComparer<string?>.Default.Equals(this.Domain, other.Domain));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaOrganizationServiceDeleteOrganizationDomainRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.OrganizationId);
        hash.Add(this.Domain);
        return hash.ToHashCode();
    }
}
