// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceOrganization : IEquatable<BetaUserServiceOrganization>
{
    /// <example>null</example>
    [JsonPropertyName("orgDomain")]
    public string? OrgDomain { get; set; }

    /// <example>null</example>
    [JsonPropertyName("orgId")]
    public string? OrgId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceOrganization? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.OrgDomain, other.OrgDomain)
                    && EqualityComparer<string?>.Default.Equals(this.OrgId, other.OrgId)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceOrganization);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.OrgDomain);
        hash.Add(this.OrgId);
        return hash.ToHashCode();
    }
}
