// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaActionServiceListExecutionsResponse : IEquatable<BetaActionServiceListExecutionsResponse>
{
    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public BetaActionServicePaginationResponse? Pagination { get; set; }

    /// <example>null</example>
    [JsonPropertyName("executions")]
    public List<BetaActionServiceExecution>? Executions { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaActionServiceListExecutionsResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaActionServicePaginationResponse?>.Default.Equals(this.Pagination, other.Pagination)
                    && EqualityComparer<List<BetaActionServiceExecution>?>.Default.Equals(this.Executions, other.Executions));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaActionServiceListExecutionsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(this.Executions);
        return hash.ToHashCode();
    }
}
