// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaFeatureServiceGetInstanceFeaturesResponse : IEquatable<BetaFeatureServiceGetInstanceFeaturesResponse>
{
    /// <example>null</example>
    [JsonPropertyName("details")]
    public BetaFeatureServiceDetails? Details { get; set; }

    /// <example>null</example>
    [JsonPropertyName("loginDefaultOrg")]
    public BetaFeatureServiceFeatureFlag? LoginDefaultOrg { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userSchema")]
    public BetaFeatureServiceFeatureFlag? UserSchema { get; set; }

    /// <example>null</example>
    [JsonPropertyName("oidcTokenExchange")]
    public BetaFeatureServiceFeatureFlag? OidcTokenExchange { get; set; }

    /// <example>null</example>
    [JsonPropertyName("improvedPerformance")]
    public BetaFeatureServiceImprovedPerformanceFeatureFlag? ImprovedPerformance { get; set; }

    /// <example>null</example>
    [JsonPropertyName("debugOidcParentError")]
    public BetaFeatureServiceFeatureFlag? DebugOidcParentError { get; set; }

    /// <example>null</example>
    [JsonPropertyName("oidcSingleV1SessionTermination")]
    public BetaFeatureServiceFeatureFlag? OidcSingleV1SessionTermination { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaFeatureServiceGetInstanceFeaturesResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaFeatureServiceDetails?>.Default.Equals(this.Details, other.Details)
                    && EqualityComparer<BetaFeatureServiceFeatureFlag?>.Default.Equals(this.LoginDefaultOrg, other.LoginDefaultOrg)
                    && EqualityComparer<BetaFeatureServiceFeatureFlag?>.Default.Equals(this.UserSchema, other.UserSchema)
                    && EqualityComparer<BetaFeatureServiceFeatureFlag?>.Default.Equals(this.OidcTokenExchange, other.OidcTokenExchange)
                    && EqualityComparer<BetaFeatureServiceImprovedPerformanceFeatureFlag?>.Default.Equals(this.ImprovedPerformance, other.ImprovedPerformance)
                    && EqualityComparer<BetaFeatureServiceFeatureFlag?>.Default.Equals(this.DebugOidcParentError, other.DebugOidcParentError)
                    && EqualityComparer<BetaFeatureServiceFeatureFlag?>.Default.Equals(this.OidcSingleV1SessionTermination, other.OidcSingleV1SessionTermination));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaFeatureServiceGetInstanceFeaturesResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Details);
        hash.Add(this.LoginDefaultOrg);
        hash.Add(this.UserSchema);
        hash.Add(this.OidcTokenExchange);
        hash.Add(this.ImprovedPerformance);
        hash.Add(this.DebugOidcParentError);
        hash.Add(this.OidcSingleV1SessionTermination);
        return hash.ToHashCode();
    }
}
