// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaUserServiceRegisterU2FResponse : IEquatable<BetaUserServiceRegisterU2FResponse>
{
    /// <example>null</example>
    [JsonPropertyName("details")]
    public BetaUserServiceDetails? Details { get; set; }

    /// <example>null</example>
    [JsonPropertyName("u2fId")]
    public string? U2fId { get; set; }

    /// <summary>
    /// `Struct` represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, `Struct`  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for `Struct` is JSON object.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("publicKeyCredentialCreationOptions")]
    public Dictionary<string, Object>? PublicKeyCredentialCreationOptions { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaUserServiceRegisterU2FResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<BetaUserServiceDetails?>.Default.Equals(
                    this.Details,
                    other.Details
                )
                    && EqualityComparer<string?>.Default.Equals(this.U2fId, other.U2fId)
                    && EqualityComparer<Dictionary<string, Object>?>.Default.Equals(
                        this.PublicKeyCredentialCreationOptions,
                        other.PublicKeyCredentialCreationOptions
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaUserServiceRegisterU2FResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Details);
        hash.Add(this.U2fId);
        hash.Add(this.PublicKeyCredentialCreationOptions);
        return hash.ToHashCode();
    }
}
