// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaWebKeyServiceRSA : IEquatable<BetaWebKeyServiceRSA>
{
    /// <example>null</example>
    [JsonPropertyName("bits")]
    public BetaWebKeyServiceRSABits? Bits { get; set; }

    /// <example>null</example>
    [JsonPropertyName("hasher")]
    public BetaWebKeyServiceRSAHasher? Hasher { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaWebKeyServiceRSA? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaWebKeyServiceRSABits?>.Default.Equals(this.Bits, other.Bits)
                    && EqualityComparer<BetaWebKeyServiceRSAHasher?>.Default.Equals(this.Hasher, other.Hasher));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaWebKeyServiceRSA);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Bits);
        hash.Add(this.Hasher);
        return hash.ToHashCode();
    }
}
