// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaInternalPermissionServiceResourceFilter : IEquatable<BetaInternalPermissionServiceResourceFilter>
{
    /// <summary>
    /// Search for administrators granted on the instance level.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instance")]
    public bool? Instance { get; set; }

    /// <summary>
    /// Search for administrators granted on a specific organization.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <summary>
    /// Search for administrators granted on a specific project grant.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("projectGrantId")]
    public string? ProjectGrantId { get; set; }

    /// <summary>
    /// Search for administrators granted on a specific project.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("projectId")]
    public string? ProjectId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaInternalPermissionServiceResourceFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.Instance, other.Instance)
                    && EqualityComparer<string?>.Default.Equals(this.OrganizationId, other.OrganizationId)
                    && EqualityComparer<string?>.Default.Equals(this.ProjectGrantId, other.ProjectGrantId)
                    && EqualityComparer<string?>.Default.Equals(this.ProjectId, other.ProjectId));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaInternalPermissionServiceResourceFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Instance);
        hash.Add(this.OrganizationId);
        hash.Add(this.ProjectGrantId);
        hash.Add(this.ProjectId);
        return hash.ToHashCode();
    }
}
