// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaUserServiceTextQueryMethodConverter))]
public enum BetaUserServiceTextQueryMethod
{
    TEXTQUERYMETHODEQUALS,

    TEXTQUERYMETHODEQUALSIGNORECASE,

    TEXTQUERYMETHODSTARTSWITH,

    TEXTQUERYMETHODSTARTSWITHIGNORECASE,

    TEXTQUERYMETHODCONTAINS,

    TEXTQUERYMETHODCONTAINSIGNORECASE,

    TEXTQUERYMETHODENDSWITH,

    TEXTQUERYMETHODENDSWITHIGNORECASE,
}

/// <summary>
/// Serializes <see cref="BetaUserServiceTextQueryMethod"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaUserServiceTextQueryMethodConverter
    : JsonConverter<BetaUserServiceTextQueryMethod>
{
    public override BetaUserServiceTextQueryMethod Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException(
                $"Expected a JSON string for enum BetaUserServiceTextQueryMethod but got {reader.TokenType}."
            );
        }

        string? value = reader.GetString();
        return value switch
        {
            "TEXT_QUERY_METHOD_EQUALS" => BetaUserServiceTextQueryMethod.TEXTQUERYMETHODEQUALS,
            "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE" =>
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE,
            "TEXT_QUERY_METHOD_STARTS_WITH" =>
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH,
            "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE" =>
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE,
            "TEXT_QUERY_METHOD_CONTAINS" => BetaUserServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS,
            "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE" =>
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE,
            "TEXT_QUERY_METHOD_ENDS_WITH" => BetaUserServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH,
            "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE" =>
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE,
            _ => throw new JsonException(
                $"Unknown value '{value}' for enum BetaUserServiceTextQueryMethod."
            ),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        BetaUserServiceTextQueryMethod value,
        JsonSerializerOptions options
    )
    {
        writer.WriteStringValue(
            value switch
            {
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODEQUALS => "TEXT_QUERY_METHOD_EQUALS",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE =>
                    "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH =>
                    "TEXT_QUERY_METHOD_STARTS_WITH",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE =>
                    "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS =>
                    "TEXT_QUERY_METHOD_CONTAINS",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE =>
                    "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH =>
                    "TEXT_QUERY_METHOD_ENDS_WITH",
                BetaUserServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE =>
                    "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE",
                _ => throw new JsonException(
                    $"Unknown value '{value}' for enum BetaUserServiceTextQueryMethod."
                ),
            }
        );
    }
}
