// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class BetaSessionServiceGetSessionResponse : IEquatable<BetaSessionServiceGetSessionResponse>
{
    /// <example>null</example>
    [JsonPropertyName("session")]
    public BetaSessionServiceSession? Session { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(BetaSessionServiceGetSessionResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<BetaSessionServiceSession?>.Default.Equals(this.Session, other.Session));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as BetaSessionServiceGetSessionResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Session);
        return hash.ToHashCode();
    }
}
