// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(BetaProjectServiceProjectGrantStateConverter))]
public enum BetaProjectServiceProjectGrantState
{
    PROJECTGRANTSTATEUNSPECIFIED,

    PROJECTGRANTSTATEACTIVE,

    PROJECTGRANTSTATEINACTIVE,
}

/// <summary>
/// Serializes <see cref="BetaProjectServiceProjectGrantState"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class BetaProjectServiceProjectGrantStateConverter : JsonConverter<BetaProjectServiceProjectGrantState>
{
    public override BetaProjectServiceProjectGrantState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum BetaProjectServiceProjectGrantState but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "PROJECT_GRANT_STATE_UNSPECIFIED" => BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEUNSPECIFIED,
            "PROJECT_GRANT_STATE_ACTIVE" => BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEACTIVE,
            "PROJECT_GRANT_STATE_INACTIVE" => BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEINACTIVE,
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaProjectServiceProjectGrantState.")
        };
    }

    public override void Write(Utf8JsonWriter writer, BetaProjectServiceProjectGrantState value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEUNSPECIFIED => "PROJECT_GRANT_STATE_UNSPECIFIED",
            BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEACTIVE => "PROJECT_GRANT_STATE_ACTIVE",
            BetaProjectServiceProjectGrantState.PROJECTGRANTSTATEINACTIVE => "PROJECT_GRANT_STATE_INACTIVE",
            _ => throw new JsonException($"Unknown value '{value}' for enum BetaProjectServiceProjectGrantState.")
        });
    }
}
