// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

/// <summary>
/// FeatureFlag is a simple boolean Feature setting, without further payload.
/// </summary>
public class FeatureServiceFeatureFlag : IEquatable<FeatureServiceFeatureFlag>
{
    /// <example>null</example>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }

    /// <example>null</example>
    [JsonPropertyName("source")]
    public FeatureServiceSource? Source { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(FeatureServiceFeatureFlag? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.Enabled, other.Enabled)
                    && EqualityComparer<FeatureServiceSource?>.Default.Equals(this.Source, other.Source));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as FeatureServiceFeatureFlag);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Enabled);
        hash.Add(this.Source);
        return hash.ToHashCode();
    }
}
