// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class IdentityProviderServiceGenericOIDCConfig : IEquatable<IdentityProviderServiceGenericOIDCConfig>
{
    /// <summary>
    /// The OIDC issuer of the identity provider.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("issuer")]
    public string? Issuer { get; set; }

    /// <summary>
    /// Client id generated by the identity provider.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <summary>
    /// The scopes requested by ZITADEL during the request on the identity  provider.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("scopes")]
    public List<string>? Scopes { get; set; }

    /// <summary>
    /// If true, provider information get mapped from the id token, not from the  userinfo endpoint.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("isIdTokenMapping")]
    public bool? IsIdTokenMapping { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(IdentityProviderServiceGenericOIDCConfig? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Issuer, other.Issuer)
                    && EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
                    && EqualityComparer<List<string>?>.Default.Equals(this.Scopes, other.Scopes)
                    && EqualityComparer<bool?>.Default.Equals(this.IsIdTokenMapping, other.IsIdTokenMapping));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as IdentityProviderServiceGenericOIDCConfig);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Issuer);
        hash.Add(this.ClientId);
        hash.Add(this.Scopes);
        hash.Add(this.IsIdTokenMapping);
        return hash.ToHashCode();
    }
}
