// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class IdentityProviderServiceOAuthConfig : IEquatable<IdentityProviderServiceOAuthConfig>
{
    /// <summary>
    /// Client id generated by the identity provider.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <summary>
    /// The endpoint where ZITADEL send the user to authenticate.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("authorizationEndpoint")]
    public string? AuthorizationEndpoint { get; set; }

    /// <summary>
    /// The endpoint where ZITADEL can get the token.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("tokenEndpoint")]
    public string? TokenEndpoint { get; set; }

    /// <summary>
    /// The endpoint where ZITADEL can get the user information.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("userEndpoint")]
    public string? UserEndpoint { get; set; }

    /// <summary>
    /// The scopes requested by ZITADEL during the request on the identity  provider.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("scopes")]
    public List<string>? Scopes { get; set; }

    /// <summary>
    /// Defines how the attribute is called where ZITADEL can get the id of the  user.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("idAttribute")]
    public string? IdAttribute { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(IdentityProviderServiceOAuthConfig? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
                    && EqualityComparer<string?>.Default.Equals(this.AuthorizationEndpoint, other.AuthorizationEndpoint)
                    && EqualityComparer<string?>.Default.Equals(this.TokenEndpoint, other.TokenEndpoint)
                    && EqualityComparer<string?>.Default.Equals(this.UserEndpoint, other.UserEndpoint)
                    && EqualityComparer<List<string>?>.Default.Equals(this.Scopes, other.Scopes)
                    && EqualityComparer<string?>.Default.Equals(this.IdAttribute, other.IdAttribute));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as IdentityProviderServiceOAuthConfig);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ClientId);
        hash.Add(this.AuthorizationEndpoint);
        hash.Add(this.TokenEndpoint);
        hash.Add(this.UserEndpoint);
        hash.Add(this.Scopes);
        hash.Add(this.IdAttribute);
        return hash.ToHashCode();
    }
}
