// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class IdentityProviderServiceAzureADConfig : IEquatable<IdentityProviderServiceAzureADConfig>
{
    /// <summary>
    /// Client id of the Azure AD application
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("tenant")]
    public IdentityProviderServiceAzureADTenant? Tenant { get; set; }

    /// <summary>
    /// Azure AD doesn't send if the email has been verified. Enable this if the  user email should always be added verified in ZITADEL (no verification  emails will be sent).
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("emailVerified")]
    public bool? EmailVerified { get; set; }

    /// <summary>
    /// The scopes requested by ZITADEL during the request to Azure AD.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("scopes")]
    public List<string>? Scopes { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(IdentityProviderServiceAzureADConfig? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
                    && EqualityComparer<IdentityProviderServiceAzureADTenant?>.Default.Equals(this.Tenant, other.Tenant)
                    && EqualityComparer<bool?>.Default.Equals(this.EmailVerified, other.EmailVerified)
                    && EqualityComparer<List<string>?>.Default.Equals(this.Scopes, other.Scopes));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as IdentityProviderServiceAzureADConfig);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ClientId);
        hash.Add(this.Tenant);
        hash.Add(this.EmailVerified);
        hash.Add(this.Scopes);
        return hash.ToHashCode();
    }
}
