// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(IdentityProviderServiceSAMLSignatureAlgorithmConverter))]
public enum IdentityProviderServiceSAMLSignatureAlgorithm
{
    SAMLSIGNATUREUNSPECIFIED,

    SAMLSIGNATURERSASHA1,

    SAMLSIGNATURERSASHA256,

    SAMLSIGNATURERSASHA512,
}

/// <summary>
/// Serializes <see cref="IdentityProviderServiceSAMLSignatureAlgorithm"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class IdentityProviderServiceSAMLSignatureAlgorithmConverter : JsonConverter<IdentityProviderServiceSAMLSignatureAlgorithm>
{
    public override IdentityProviderServiceSAMLSignatureAlgorithm Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum IdentityProviderServiceSAMLSignatureAlgorithm but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "SAML_SIGNATURE_UNSPECIFIED" => IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATUREUNSPECIFIED,
            "SAML_SIGNATURE_RSA_SHA1" => IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA1,
            "SAML_SIGNATURE_RSA_SHA256" => IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA256,
            "SAML_SIGNATURE_RSA_SHA512" => IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA512,
            _ => throw new JsonException($"Unknown value '{value}' for enum IdentityProviderServiceSAMLSignatureAlgorithm.")
        };
    }

    public override void Write(Utf8JsonWriter writer, IdentityProviderServiceSAMLSignatureAlgorithm value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATUREUNSPECIFIED => "SAML_SIGNATURE_UNSPECIFIED",
            IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA1 => "SAML_SIGNATURE_RSA_SHA1",
            IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA256 => "SAML_SIGNATURE_RSA_SHA256",
            IdentityProviderServiceSAMLSignatureAlgorithm.SAMLSIGNATURERSASHA512 => "SAML_SIGNATURE_RSA_SHA512",
            _ => throw new JsonException($"Unknown value '{value}' for enum IdentityProviderServiceSAMLSignatureAlgorithm.")
        });
    }
}
