// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum IdentityProviderServiceIDPState
{
    [JsonStringEnumMemberName("IDP_STATE_UNSPECIFIED")]
    IDPSTATEUNSPECIFIED,

    [JsonStringEnumMemberName("IDP_STATE_ACTIVE")]
    IDPSTATEACTIVE,

    [JsonStringEnumMemberName("IDP_STATE_INACTIVE")]
    IDPSTATEINACTIVE,

    [JsonStringEnumMemberName("IDP_STATE_REMOVED")]
    IDPSTATEREMOVED,

    [JsonStringEnumMemberName("IDP_STATE_MIGRATED")]
    IDPSTATEMIGRATED,
}
