// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(IdentityProviderServiceAutoLinkingOptionConverter))]
public enum IdentityProviderServiceAutoLinkingOption
{
    AUTOLINKINGOPTIONUNSPECIFIED,

    AUTOLINKINGOPTIONUSERNAME,

    AUTOLINKINGOPTIONEMAIL,
}

/// <summary>
/// Serializes <see cref="IdentityProviderServiceAutoLinkingOption"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class IdentityProviderServiceAutoLinkingOptionConverter : JsonConverter<IdentityProviderServiceAutoLinkingOption>
{
    public override IdentityProviderServiceAutoLinkingOption Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum IdentityProviderServiceAutoLinkingOption but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "AUTO_LINKING_OPTION_UNSPECIFIED" => IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONUNSPECIFIED,
            "AUTO_LINKING_OPTION_USERNAME" => IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONUSERNAME,
            "AUTO_LINKING_OPTION_EMAIL" => IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONEMAIL,
            _ => throw new JsonException($"Unknown value '{value}' for enum IdentityProviderServiceAutoLinkingOption.")
        };
    }

    public override void Write(Utf8JsonWriter writer, IdentityProviderServiceAutoLinkingOption value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONUNSPECIFIED => "AUTO_LINKING_OPTION_UNSPECIFIED",
            IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONUSERNAME => "AUTO_LINKING_OPTION_USERNAME",
            IdentityProviderServiceAutoLinkingOption.AUTOLINKINGOPTIONEMAIL => "AUTO_LINKING_OPTION_EMAIL",
            _ => throw new JsonException($"Unknown value '{value}' for enum IdentityProviderServiceAutoLinkingOption.")
        });
    }
}
