// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class InstanceServiceRemoveCustomDomainRequest : IEquatable<InstanceServiceRemoveCustomDomainRequest>
{
    /// <summary>
    /// InstanceID is the unique ID of the instance from which the domain will be removed.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instanceId")]
    public string? InstanceId { get; set; }

    /// <summary>
    /// CustomDomain is the the domain to remove from the instance.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("customDomain")]
    public string? CustomDomain { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(InstanceServiceRemoveCustomDomainRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.InstanceId, other.InstanceId)
                    && EqualityComparer<string?>.Default.Equals(this.CustomDomain, other.CustomDomain));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as InstanceServiceRemoveCustomDomainRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.InstanceId);
        hash.Add(this.CustomDomain);
        return hash.ToHashCode();
    }
}
