// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(InstanceServiceStateConverter))]
public enum InstanceServiceState
{
    STATEUNSPECIFIED,

    STATECREATING,

    STATERUNNING,

    STATESTOPPING,

    STATESTOPPED,
}

/// <summary>
/// Serializes <see cref="InstanceServiceState"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class InstanceServiceStateConverter : JsonConverter<InstanceServiceState>
{
    public override InstanceServiceState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum InstanceServiceState but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "STATE_UNSPECIFIED" => InstanceServiceState.STATEUNSPECIFIED,
            "STATE_CREATING" => InstanceServiceState.STATECREATING,
            "STATE_RUNNING" => InstanceServiceState.STATERUNNING,
            "STATE_STOPPING" => InstanceServiceState.STATESTOPPING,
            "STATE_STOPPED" => InstanceServiceState.STATESTOPPED,
            _ => throw new JsonException($"Unknown value '{value}' for enum InstanceServiceState.")
        };
    }

    public override void Write(Utf8JsonWriter writer, InstanceServiceState value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            InstanceServiceState.STATEUNSPECIFIED => "STATE_UNSPECIFIED",
            InstanceServiceState.STATECREATING => "STATE_CREATING",
            InstanceServiceState.STATERUNNING => "STATE_RUNNING",
            InstanceServiceState.STATESTOPPING => "STATE_STOPPING",
            InstanceServiceState.STATESTOPPED => "STATE_STOPPED",
            _ => throw new JsonException($"Unknown value '{value}' for enum InstanceServiceState.")
        });
    }
}
