// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class InstanceServiceListInstancesResponse : IEquatable<InstanceServiceListInstancesResponse>
{
    /// <summary>
    /// The instances matching the query.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instances")]
    public List<InstanceServiceInstance>? Instances { get; set; }

    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public InstanceServicePaginationResponse? Pagination { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(InstanceServiceListInstancesResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<List<InstanceServiceInstance>?>.Default.Equals(this.Instances, other.Instances)
                    && EqualityComparer<InstanceServicePaginationResponse?>.Default.Equals(this.Pagination, other.Pagination));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as InstanceServiceListInstancesResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Instances);
        hash.Add(this.Pagination);
        return hash.ToHashCode();
    }
}
