// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(InstanceServiceDomainFieldNameConverter))]
public enum InstanceServiceDomainFieldName
{
    DOMAINFIELDNAMEUNSPECIFIED,

    DOMAINFIELDNAMEDOMAIN,

    DOMAINFIELDNAMEPRIMARY,

    DOMAINFIELDNAMEGENERATED,

    DOMAINFIELDNAMECREATIONDATE,
}

/// <summary>
/// Serializes <see cref="InstanceServiceDomainFieldName"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class InstanceServiceDomainFieldNameConverter : JsonConverter<InstanceServiceDomainFieldName>
{
    public override InstanceServiceDomainFieldName Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum InstanceServiceDomainFieldName but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "DOMAIN_FIELD_NAME_UNSPECIFIED" => InstanceServiceDomainFieldName.DOMAINFIELDNAMEUNSPECIFIED,
            "DOMAIN_FIELD_NAME_DOMAIN" => InstanceServiceDomainFieldName.DOMAINFIELDNAMEDOMAIN,
            "DOMAIN_FIELD_NAME_PRIMARY" => InstanceServiceDomainFieldName.DOMAINFIELDNAMEPRIMARY,
            "DOMAIN_FIELD_NAME_GENERATED" => InstanceServiceDomainFieldName.DOMAINFIELDNAMEGENERATED,
            "DOMAIN_FIELD_NAME_CREATION_DATE" => InstanceServiceDomainFieldName.DOMAINFIELDNAMECREATIONDATE,
            _ => throw new JsonException($"Unknown value '{value}' for enum InstanceServiceDomainFieldName.")
        };
    }

    public override void Write(Utf8JsonWriter writer, InstanceServiceDomainFieldName value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            InstanceServiceDomainFieldName.DOMAINFIELDNAMEUNSPECIFIED => "DOMAIN_FIELD_NAME_UNSPECIFIED",
            InstanceServiceDomainFieldName.DOMAINFIELDNAMEDOMAIN => "DOMAIN_FIELD_NAME_DOMAIN",
            InstanceServiceDomainFieldName.DOMAINFIELDNAMEPRIMARY => "DOMAIN_FIELD_NAME_PRIMARY",
            InstanceServiceDomainFieldName.DOMAINFIELDNAMEGENERATED => "DOMAIN_FIELD_NAME_GENERATED",
            InstanceServiceDomainFieldName.DOMAINFIELDNAMECREATIONDATE => "DOMAIN_FIELD_NAME_CREATION_DATE",
            _ => throw new JsonException($"Unknown value '{value}' for enum InstanceServiceDomainFieldName.")
        });
    }
}
