// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class InstanceServiceUpdateInstanceRequest : IEquatable<InstanceServiceUpdateInstanceRequest>
{
    /// <summary>
    /// InstanceID is the unique ID of the instance to be updated.  If not set, the instance in the current context (e.g. identified by the host header) will be changed.  If an ID is set, the caller must have additional permissions.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instanceId")]
    public string? InstanceId { get; set; }

    /// <summary>
    /// InstanceName is the new name of the instance to be set.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("instanceName")]
    public string? InstanceName { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(InstanceServiceUpdateInstanceRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.InstanceId, other.InstanceId)
                    && EqualityComparer<string?>.Default.Equals(this.InstanceName, other.InstanceName));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as InstanceServiceUpdateInstanceRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.InstanceId);
        hash.Add(this.InstanceName);
        return hash.ToHashCode();
    }
}
