// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class InternalPermissionServiceProjectGrant
    : IEquatable<InternalPermissionServiceProjectGrant>
{
    /// <summary>
    /// ProjectID is the unique identifier of the project the project grant belongs to.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("projectId")]
    public string? ProjectId { get; set; }

    /// <summary>
    /// OrganizationID is the unique identifier of the organization the project was granted to  and on which the administrator role should be granted.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(InternalPermissionServiceProjectGrant? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.ProjectId, other.ProjectId)
                    && EqualityComparer<string?>.Default.Equals(
                        this.OrganizationId,
                        other.OrganizationId
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as InternalPermissionServiceProjectGrant);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.ProjectId);
        hash.Add(this.OrganizationId);
        return hash.ToHashCode();
    }
}
