// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class InternalPermissionServiceAdministratorSearchFilter : IEquatable<InternalPermissionServiceAdministratorSearchFilter>
{
    /// <example>null</example>
    [JsonPropertyName("and")]
    public InternalPermissionServiceAndFilter? And { get; set; }

    /// <example>null</example>
    [JsonPropertyName("changeDate")]
    public InternalPermissionServiceTimestampFilter? ChangeDate { get; set; }

    /// <example>null</example>
    [JsonPropertyName("creationDate")]
    public InternalPermissionServiceTimestampFilter? CreationDate { get; set; }

    /// <example>null</example>
    [JsonPropertyName("inUserIdsFilter")]
    public InternalPermissionServiceInIDsFilter? InUserIdsFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("not")]
    public InternalPermissionServiceNotFilter? Not { get; set; }

    /// <example>null</example>
    [JsonPropertyName("or")]
    public InternalPermissionServiceOrFilter? Or { get; set; }

    /// <example>null</example>
    [JsonPropertyName("resource")]
    public InternalPermissionServiceResourceFilter? Resource { get; set; }

    /// <example>null</example>
    [JsonPropertyName("role")]
    public InternalPermissionServiceRoleFilter? Role { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userDisplayName")]
    public InternalPermissionServiceUserDisplayNameFilter? UserDisplayName { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userOrganizationId")]
    public InternalPermissionServiceIDFilter? UserOrganizationId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userPreferredLoginName")]
    public InternalPermissionServiceUserPreferredLoginNameFilter? UserPreferredLoginName { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(InternalPermissionServiceAdministratorSearchFilter? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<InternalPermissionServiceAndFilter?>.Default.Equals(this.And, other.And)
                    && EqualityComparer<InternalPermissionServiceTimestampFilter?>.Default.Equals(this.ChangeDate, other.ChangeDate)
                    && EqualityComparer<InternalPermissionServiceTimestampFilter?>.Default.Equals(this.CreationDate, other.CreationDate)
                    && EqualityComparer<InternalPermissionServiceInIDsFilter?>.Default.Equals(this.InUserIdsFilter, other.InUserIdsFilter)
                    && EqualityComparer<InternalPermissionServiceNotFilter?>.Default.Equals(this.Not, other.Not)
                    && EqualityComparer<InternalPermissionServiceOrFilter?>.Default.Equals(this.Or, other.Or)
                    && EqualityComparer<InternalPermissionServiceResourceFilter?>.Default.Equals(this.Resource, other.Resource)
                    && EqualityComparer<InternalPermissionServiceRoleFilter?>.Default.Equals(this.Role, other.Role)
                    && EqualityComparer<InternalPermissionServiceUserDisplayNameFilter?>.Default.Equals(this.UserDisplayName, other.UserDisplayName)
                    && EqualityComparer<InternalPermissionServiceIDFilter?>.Default.Equals(this.UserOrganizationId, other.UserOrganizationId)
                    && EqualityComparer<InternalPermissionServiceUserPreferredLoginNameFilter?>.Default.Equals(this.UserPreferredLoginName, other.UserPreferredLoginName));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as InternalPermissionServiceAdministratorSearchFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.And);
        hash.Add(this.ChangeDate);
        hash.Add(this.CreationDate);
        hash.Add(this.InUserIdsFilter);
        hash.Add(this.Not);
        hash.Add(this.Or);
        hash.Add(this.Resource);
        hash.Add(this.Role);
        hash.Add(this.UserDisplayName);
        hash.Add(this.UserOrganizationId);
        hash.Add(this.UserPreferredLoginName);
        return hash.ToHashCode();
    }
}
