// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OIDCServiceAuthorizeOrDenyDeviceAuthorizationRequest : IEquatable<OIDCServiceAuthorizeOrDenyDeviceAuthorizationRequest>
{
    /// <summary>
    /// The device authorization id returned when submitting the user code.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("deviceAuthorizationId")]
    public string? DeviceAuthorizationId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("deny")]
    public Object? Deny { get; set; }

    /// <example>null</example>
    [JsonPropertyName("session")]
    public OIDCServiceSession? Session { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OIDCServiceAuthorizeOrDenyDeviceAuthorizationRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.DeviceAuthorizationId, other.DeviceAuthorizationId)
                    && EqualityComparer<Object?>.Default.Equals(this.Deny, other.Deny)
                    && EqualityComparer<OIDCServiceSession?>.Default.Equals(this.Session, other.Session));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OIDCServiceAuthorizeOrDenyDeviceAuthorizationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.DeviceAuthorizationId);
        hash.Add(this.Deny);
        hash.Add(this.Session);
        return hash.ToHashCode();
    }
}
