// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OIDCServiceDeviceAuthorizationRequest
    : IEquatable<OIDCServiceDeviceAuthorizationRequest>
{
    /// <summary>
    /// The unique identifier of the device authorization request to be used for authorizing or denying the request.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// The client_id of the application that initiated the device authorization request.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; set; }

    /// <summary>
    /// The scopes requested by the application.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("scope")]
    public List<string>? Scope { get; set; }

    /// <summary>
    /// Name of the client application.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("appName")]
    public string? AppName { get; set; }

    /// <summary>
    /// Name of the project the client application is part of.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("projectName")]
    public string? ProjectName { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OIDCServiceDeviceAuthorizationRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Id, other.Id)
                    && EqualityComparer<string?>.Default.Equals(this.ClientId, other.ClientId)
                    && EqualityComparer<List<string>?>.Default.Equals(this.Scope, other.Scope)
                    && EqualityComparer<string?>.Default.Equals(this.AppName, other.AppName)
                    && EqualityComparer<string?>.Default.Equals(this.ProjectName, other.ProjectName)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OIDCServiceDeviceAuthorizationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Id);
        hash.Add(this.ClientId);
        hash.Add(this.Scope);
        hash.Add(this.AppName);
        hash.Add(this.ProjectName);
        return hash.ToHashCode();
    }
}
