// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(OIDCServicePromptConverter))]
public enum OIDCServicePrompt
{
    PROMPTUNSPECIFIED,

    PROMPTNONE,

    PROMPTLOGIN,

    PROMPTCONSENT,

    PROMPTSELECTACCOUNT,

    PROMPTCREATE,
}

/// <summary>
/// Serializes <see cref="OIDCServicePrompt"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class OIDCServicePromptConverter : JsonConverter<OIDCServicePrompt>
{
    public override OIDCServicePrompt Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum OIDCServicePrompt but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "PROMPT_UNSPECIFIED" => OIDCServicePrompt.PROMPTUNSPECIFIED,
            "PROMPT_NONE" => OIDCServicePrompt.PROMPTNONE,
            "PROMPT_LOGIN" => OIDCServicePrompt.PROMPTLOGIN,
            "PROMPT_CONSENT" => OIDCServicePrompt.PROMPTCONSENT,
            "PROMPT_SELECT_ACCOUNT" => OIDCServicePrompt.PROMPTSELECTACCOUNT,
            "PROMPT_CREATE" => OIDCServicePrompt.PROMPTCREATE,
            _ => throw new JsonException($"Unknown value '{value}' for enum OIDCServicePrompt.")
        };
    }

    public override void Write(Utf8JsonWriter writer, OIDCServicePrompt value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            OIDCServicePrompt.PROMPTUNSPECIFIED => "PROMPT_UNSPECIFIED",
            OIDCServicePrompt.PROMPTNONE => "PROMPT_NONE",
            OIDCServicePrompt.PROMPTLOGIN => "PROMPT_LOGIN",
            OIDCServicePrompt.PROMPTCONSENT => "PROMPT_CONSENT",
            OIDCServicePrompt.PROMPTSELECTACCOUNT => "PROMPT_SELECT_ACCOUNT",
            OIDCServicePrompt.PROMPTCREATE => "PROMPT_CREATE",
            _ => throw new JsonException($"Unknown value '{value}' for enum OIDCServicePrompt.")
        });
    }
}
