// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OrganizationServiceOrganizationStateQuery : IEquatable<OrganizationServiceOrganizationStateQuery>
{
    /// <example>null</example>
    [JsonPropertyName("state")]
    public OrganizationServiceOrganizationState? State { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OrganizationServiceOrganizationStateQuery? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<OrganizationServiceOrganizationState?>.Default.Equals(this.State, other.State));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OrganizationServiceOrganizationStateQuery);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.State);
        return hash.ToHashCode();
    }
}
