// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(OrganizationServiceTextQueryMethodConverter))]
public enum OrganizationServiceTextQueryMethod
{
    TEXTQUERYMETHODEQUALS,

    TEXTQUERYMETHODEQUALSIGNORECASE,

    TEXTQUERYMETHODSTARTSWITH,

    TEXTQUERYMETHODSTARTSWITHIGNORECASE,

    TEXTQUERYMETHODCONTAINS,

    TEXTQUERYMETHODCONTAINSIGNORECASE,

    TEXTQUERYMETHODENDSWITH,

    TEXTQUERYMETHODENDSWITHIGNORECASE,
}

/// <summary>
/// Serializes <see cref="OrganizationServiceTextQueryMethod"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class OrganizationServiceTextQueryMethodConverter : JsonConverter<OrganizationServiceTextQueryMethod>
{
    public override OrganizationServiceTextQueryMethod Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum OrganizationServiceTextQueryMethod but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "TEXT_QUERY_METHOD_EQUALS" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALS,
            "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE,
            "TEXT_QUERY_METHOD_STARTS_WITH" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH,
            "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE,
            "TEXT_QUERY_METHOD_CONTAINS" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS,
            "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE,
            "TEXT_QUERY_METHOD_ENDS_WITH" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH,
            "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE" => OrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE,
            _ => throw new JsonException($"Unknown value '{value}' for enum OrganizationServiceTextQueryMethod.")
        };
    }

    public override void Write(Utf8JsonWriter writer, OrganizationServiceTextQueryMethod value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALS => "TEXT_QUERY_METHOD_EQUALS",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODEQUALSIGNORECASE => "TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITH => "TEXT_QUERY_METHOD_STARTS_WITH",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODSTARTSWITHIGNORECASE => "TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINS => "TEXT_QUERY_METHOD_CONTAINS",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODCONTAINSIGNORECASE => "TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITH => "TEXT_QUERY_METHOD_ENDS_WITH",
            OrganizationServiceTextQueryMethod.TEXTQUERYMETHODENDSWITHIGNORECASE => "TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE",
            _ => throw new JsonException($"Unknown value '{value}' for enum OrganizationServiceTextQueryMethod.")
        });
    }
}
