// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OrganizationServiceListOrganizationMetadataResponse : IEquatable<OrganizationServiceListOrganizationMetadataResponse>
{
    [JsonPropertyName("pagination")]
    public OrganizationServicePaginationResponse? Pagination { get; set; }

    /// <summary>
    /// Metadata is a list of organization metadata that matched the query.
    /// </summary>
    [JsonPropertyName("metadata")]
    public List<OrganizationServiceMetadata>? Metadata { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OrganizationServiceListOrganizationMetadataResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<OrganizationServicePaginationResponse?>.Default.Equals(this.Pagination, other.Pagination)
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(this.Metadata, other.Metadata));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OrganizationServiceListOrganizationMetadataResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.Metadata));
        return hash.ToHashCode();
    }
}
