// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OrganizationServiceDeleteOrganizationDomainRequest
    : IEquatable<OrganizationServiceDeleteOrganizationDomainRequest>
{
    /// <summary>
    /// OrganizationID is the unique identifier of the organization from which the domain is to be deleted.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <summary>
    /// Domain is the full qualified domain name to be deleted from the organization.  Note that if the domain is used as suffix for user logins,  those users will not be able to log in anymore. They have to use another domain instead.  Also if the domain was used for domain discovery,  users will not be able to find the organization by the domain anymore.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("domain")]
    public string? Domain { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OrganizationServiceDeleteOrganizationDomainRequest? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(
                    this.OrganizationId,
                    other.OrganizationId
                ) && EqualityComparer<string?>.Default.Equals(this.Domain, other.Domain)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OrganizationServiceDeleteOrganizationDomainRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.OrganizationId);
        hash.Add(this.Domain);
        return hash.ToHashCode();
    }
}
