// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OrganizationServiceListOrganizationDomainsResponse : IEquatable<OrganizationServiceListOrganizationDomainsResponse>
{
    [JsonPropertyName("pagination")]
    public OrganizationServicePaginationResponse? Pagination { get; set; }

    /// <summary>
    /// Domains is a list of fully qualified domain names registered to the organization matching the query.
    /// </summary>
    [JsonPropertyName("domains")]
    public List<OrganizationServiceDomain>? Domains { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OrganizationServiceListOrganizationDomainsResponse? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<OrganizationServicePaginationResponse?>.Default.Equals(this.Pagination, other.Pagination)
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(this.Domains, other.Domains));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OrganizationServiceListOrganizationDomainsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.Domains));
        return hash.ToHashCode();
    }
}
