// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class OrganizationServiceAdmin : IEquatable<OrganizationServiceAdmin>
{
    /// <summary>
    /// specify Org Member Roles for the provided user (default is ORG_OWNER if roles are empty)
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("roles")]
    public List<string>? Roles { get; set; }

    /// <example>null</example>
    [JsonPropertyName("human")]
    public OrganizationServiceAddHumanUserRequest? Human { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userId")]
    public string? UserId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(OrganizationServiceAdmin? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<List<string>?>.Default.Equals(this.Roles, other.Roles)
                    && EqualityComparer<OrganizationServiceAddHumanUserRequest?>.Default.Equals(
                        this.Human,
                        other.Human
                    )
                    && EqualityComparer<string?>.Default.Equals(this.UserId, other.UserId)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as OrganizationServiceAdmin);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Roles);
        hash.Add(this.Human);
        hash.Add(this.UserId);
        return hash.ToHashCode();
    }
}
