// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ProjectServiceGrantedProjectState
{
    [JsonStringEnumMemberName("GRANTED_PROJECT_STATE_UNSPECIFIED")]
    GRANTEDPROJECTSTATEUNSPECIFIED,

    [JsonStringEnumMemberName("GRANTED_PROJECT_STATE_ACTIVE")]
    GRANTEDPROJECTSTATEACTIVE,

    [JsonStringEnumMemberName("GRANTED_PROJECT_STATE_INACTIVE")]
    GRANTEDPROJECTSTATEINACTIVE,
}
