// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ProjectServiceListProjectRolesResponse
    : IEquatable<ProjectServiceListProjectRolesResponse>
{
    [JsonPropertyName("pagination")]
    public ProjectServicePaginationResponse? Pagination { get; set; }

    /// <summary>
    /// ProjectRoles is a list of roles matching the query.
    /// </summary>
    [JsonPropertyName("projectRoles")]
    public List<ProjectServiceProjectRole>? ProjectRoles { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ProjectServiceListProjectRolesResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<ProjectServicePaginationResponse?>.Default.Equals(
                    this.Pagination,
                    other.Pagination
                )
                    && global::Zitadel.Client.ObjectSerializer.StructuralEquals(
                        this.ProjectRoles,
                        other.ProjectRoles
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ProjectServiceListProjectRolesResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(global::Zitadel.Client.ObjectSerializer.StructuralHashCode(this.ProjectRoles));
        return hash.ToHashCode();
    }
}
