// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(ProjectServiceProjectGrantStateConverter))]
public enum ProjectServiceProjectGrantState
{
    PROJECTGRANTSTATEUNSPECIFIED,

    PROJECTGRANTSTATEACTIVE,

    PROJECTGRANTSTATEINACTIVE,
}

/// <summary>
/// Serializes <see cref="ProjectServiceProjectGrantState"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class ProjectServiceProjectGrantStateConverter
    : JsonConverter<ProjectServiceProjectGrantState>
{
    public override ProjectServiceProjectGrantState Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException(
                $"Expected a JSON string for enum ProjectServiceProjectGrantState but got {reader.TokenType}."
            );
        }

        string? value = reader.GetString();
        return value switch
        {
            "PROJECT_GRANT_STATE_UNSPECIFIED" =>
                ProjectServiceProjectGrantState.PROJECTGRANTSTATEUNSPECIFIED,
            "PROJECT_GRANT_STATE_ACTIVE" => ProjectServiceProjectGrantState.PROJECTGRANTSTATEACTIVE,
            "PROJECT_GRANT_STATE_INACTIVE" =>
                ProjectServiceProjectGrantState.PROJECTGRANTSTATEINACTIVE,
            _ => throw new JsonException(
                $"Unknown value '{value}' for enum ProjectServiceProjectGrantState."
            ),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ProjectServiceProjectGrantState value,
        JsonSerializerOptions options
    )
    {
        writer.WriteStringValue(
            value switch
            {
                ProjectServiceProjectGrantState.PROJECTGRANTSTATEUNSPECIFIED =>
                    "PROJECT_GRANT_STATE_UNSPECIFIED",
                ProjectServiceProjectGrantState.PROJECTGRANTSTATEACTIVE =>
                    "PROJECT_GRANT_STATE_ACTIVE",
                ProjectServiceProjectGrantState.PROJECTGRANTSTATEINACTIVE =>
                    "PROJECT_GRANT_STATE_INACTIVE",
                _ => throw new JsonException(
                    $"Unknown value '{value}' for enum ProjectServiceProjectGrantState."
                ),
            }
        );
    }
}
