// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class ProjectServiceListProjectGrantsResponse
    : IEquatable<ProjectServiceListProjectGrantsResponse>
{
    /// <example>null</example>
    [JsonPropertyName("pagination")]
    public ProjectServicePaginationResponse? Pagination { get; set; }

    /// <summary>
    /// ProjectGrants is a list of project grants matching the query.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("projectGrants")]
    public List<ProjectServiceProjectGrant>? ProjectGrants { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(ProjectServiceListProjectGrantsResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<ProjectServicePaginationResponse?>.Default.Equals(
                    this.Pagination,
                    other.Pagination
                )
                    && EqualityComparer<List<ProjectServiceProjectGrant>?>.Default.Equals(
                        this.ProjectGrants,
                        other.ProjectGrants
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as ProjectServiceListProjectGrantsResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Pagination);
        hash.Add(this.ProjectGrants);
        return hash.ToHashCode();
    }
}
