// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SessionServiceCreateSessionResponse : IEquatable<SessionServiceCreateSessionResponse>
{
    /// <example>null</example>
    [JsonPropertyName("details")]
    public SessionServiceDetails? Details { get; set; }

    /// <summary>
    /// Unique identifier of the session.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("sessionId")]
    public string? SessionId { get; set; }

    /// <summary>
    /// The current token of the session, which is required for using the session as authentication,  e.g.when authenticating an OIDC auth request or SAML request.  Additionally, the session token can be used as OAuth2 access token to authenticate against  the ZITADEL APIs.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("sessionToken")]
    public string? SessionToken { get; set; }

    /// <example>null</example>
    [JsonPropertyName("challenges")]
    public SessionServiceChallenges? Challenges { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SessionServiceCreateSessionResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<SessionServiceDetails?>.Default.Equals(
                    this.Details,
                    other.Details
                )
                    && EqualityComparer<string?>.Default.Equals(this.SessionId, other.SessionId)
                    && EqualityComparer<string?>.Default.Equals(
                        this.SessionToken,
                        other.SessionToken
                    )
                    && EqualityComparer<SessionServiceChallenges?>.Default.Equals(
                        this.Challenges,
                        other.Challenges
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SessionServiceCreateSessionResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Details);
        hash.Add(this.SessionId);
        hash.Add(this.SessionToken);
        hash.Add(this.Challenges);
        return hash.ToHashCode();
    }
}
