// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SessionServiceChecks : IEquatable<SessionServiceChecks>
{
    [JsonPropertyName("user")]
    public SessionServiceCheckUser? User { get; set; }

    [JsonPropertyName("password")]
    public SessionServiceCheckPassword? Password { get; set; }

    [JsonPropertyName("webAuthN")]
    public SessionServiceCheckWebAuthN? WebAuthN { get; set; }

    [JsonPropertyName("idpIntent")]
    public SessionServiceCheckIDPIntent? IdpIntent { get; set; }

    [JsonPropertyName("totp")]
    public SessionServiceCheckTOTP? Totp { get; set; }

    [JsonPropertyName("otpSms")]
    public SessionServiceCheckOTP? OtpSms { get; set; }

    [JsonPropertyName("otpEmail")]
    public SessionServiceCheckOTP? OtpEmail { get; set; }

    [JsonPropertyName("recoveryCode")]
    public SessionServiceCheckRecoveryCode? RecoveryCode { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SessionServiceChecks? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<SessionServiceCheckUser?>.Default.Equals(this.User, other.User)
                    && EqualityComparer<SessionServiceCheckPassword?>.Default.Equals(this.Password, other.Password)
                    && EqualityComparer<SessionServiceCheckWebAuthN?>.Default.Equals(this.WebAuthN, other.WebAuthN)
                    && EqualityComparer<SessionServiceCheckIDPIntent?>.Default.Equals(this.IdpIntent, other.IdpIntent)
                    && EqualityComparer<SessionServiceCheckTOTP?>.Default.Equals(this.Totp, other.Totp)
                    && EqualityComparer<SessionServiceCheckOTP?>.Default.Equals(this.OtpSms, other.OtpSms)
                    && EqualityComparer<SessionServiceCheckOTP?>.Default.Equals(this.OtpEmail, other.OtpEmail)
                    && EqualityComparer<SessionServiceCheckRecoveryCode?>.Default.Equals(this.RecoveryCode, other.RecoveryCode));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SessionServiceChecks);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.User);
        hash.Add(this.Password);
        hash.Add(this.WebAuthN);
        hash.Add(this.IdpIntent);
        hash.Add(this.Totp);
        hash.Add(this.OtpSms);
        hash.Add(this.OtpEmail);
        hash.Add(this.RecoveryCode);
        return hash.ToHashCode();
    }
}
