// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SettingsServiceGetHostedLoginTranslationRequest : IEquatable<SettingsServiceGetHostedLoginTranslationRequest>
{
    /// <summary>
    /// The locale of the translations to be returned.  Needs to be a BCP 47 language tag (e.g. \"en\", \"de\", \"fr-CH\").
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("locale")]
    public string? Locale { get; set; }

    /// <summary>
    /// if set to true, higher levels are ignored, if false higher levels are merged into the file
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("ignoreInheritance")]
    public bool? IgnoreInheritance { get; set; }

    /// <example>null</example>
    [JsonPropertyName("instance")]
    public bool? Instance { get; set; }

    /// <example>null</example>
    [JsonPropertyName("organizationId")]
    public string? OrganizationId { get; set; }

    /// <example>null</example>
    [JsonPropertyName("system")]
    public bool? System { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SettingsServiceGetHostedLoginTranslationRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Locale, other.Locale)
                    && EqualityComparer<bool?>.Default.Equals(this.IgnoreInheritance, other.IgnoreInheritance)
                    && EqualityComparer<bool?>.Default.Equals(this.Instance, other.Instance)
                    && EqualityComparer<string?>.Default.Equals(this.OrganizationId, other.OrganizationId)
                    && EqualityComparer<bool?>.Default.Equals(this.System, other.System));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SettingsServiceGetHostedLoginTranslationRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Locale);
        hash.Add(this.IgnoreInheritance);
        hash.Add(this.Instance);
        hash.Add(this.OrganizationId);
        hash.Add(this.System);
        return hash.ToHashCode();
    }
}
