// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SettingsServiceSecuritySettings : IEquatable<SettingsServiceSecuritySettings>
{
    /// <example>null</example>
    [JsonPropertyName("embeddedIframe")]
    public SettingsServiceEmbeddedIframeSettings? EmbeddedIframe { get; set; }

    /// <summary>
    /// If enabled, users are allowed to impersonate other users.  The impersonator needs the appropriate `*_IMPERSONATOR` roles assigned as well\".
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("enableImpersonation")]
    public bool? EnableImpersonation { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SettingsServiceSecuritySettings? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<SettingsServiceEmbeddedIframeSettings?>.Default.Equals(this.EmbeddedIframe, other.EmbeddedIframe)
                    && EqualityComparer<bool?>.Default.Equals(this.EnableImpersonation, other.EnableImpersonation));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SettingsServiceSecuritySettings);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.EmbeddedIframe);
        hash.Add(this.EnableImpersonation);
        return hash.ToHashCode();
    }
}
