// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SettingsServiceRequestContext : IEquatable<SettingsServiceRequestContext>
{
    /// <example>null</example>
    [JsonPropertyName("instance")]
    public bool? Instance { get; set; }

    /// <example>null</example>
    [JsonPropertyName("orgId")]
    public string? OrgId { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SettingsServiceRequestContext? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.Instance, other.Instance)
                    && EqualityComparer<string?>.Default.Equals(this.OrgId, other.OrgId));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SettingsServiceRequestContext);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Instance);
        hash.Add(this.OrgId);
        return hash.ToHashCode();
    }
}
