// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SettingsServiceGetActiveIdentityProvidersRequest : IEquatable<SettingsServiceGetActiveIdentityProvidersRequest>
{
    /// <example>null</example>
    [JsonPropertyName("ctx")]
    public SettingsServiceRequestContext? Ctx { get; set; }

    /// <example>null</example>
    [JsonPropertyName("creationAllowed")]
    public bool? CreationAllowed { get; set; }

    /// <example>null</example>
    [JsonPropertyName("linkingAllowed")]
    public bool? LinkingAllowed { get; set; }

    /// <example>null</example>
    [JsonPropertyName("autoCreation")]
    public bool? AutoCreation { get; set; }

    /// <example>null</example>
    [JsonPropertyName("autoLinking")]
    public bool? AutoLinking { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SettingsServiceGetActiveIdentityProvidersRequest? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<SettingsServiceRequestContext?>.Default.Equals(this.Ctx, other.Ctx)
                    && EqualityComparer<bool?>.Default.Equals(this.CreationAllowed, other.CreationAllowed)
                    && EqualityComparer<bool?>.Default.Equals(this.LinkingAllowed, other.LinkingAllowed)
                    && EqualityComparer<bool?>.Default.Equals(this.AutoCreation, other.AutoCreation)
                    && EqualityComparer<bool?>.Default.Equals(this.AutoLinking, other.AutoLinking));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SettingsServiceGetActiveIdentityProvidersRequest);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Ctx);
        hash.Add(this.CreationAllowed);
        hash.Add(this.LinkingAllowed);
        hash.Add(this.AutoCreation);
        hash.Add(this.AutoLinking);
        return hash.ToHashCode();
    }
}
