// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(SettingsServiceResourceOwnerTypeConverter))]
public enum SettingsServiceResourceOwnerType
{
    RESOURCEOWNERTYPEUNSPECIFIED,

    RESOURCEOWNERTYPEINSTANCE,

    RESOURCEOWNERTYPEORG,
}

/// <summary>
/// Serializes <see cref="SettingsServiceResourceOwnerType"/> to and from its OpenAPI wire string
/// values. This generated converter replaces the .NET 9+
/// <c>[JsonStringEnumMemberName]</c> attribute so the client targets net8.0
/// (LTS); unknown values throw a <see cref="JsonException"/>, matching the
/// strict behaviour of the framework string-enum converter.
/// </summary>
internal sealed class SettingsServiceResourceOwnerTypeConverter : JsonConverter<SettingsServiceResourceOwnerType>
{
    public override SettingsServiceResourceOwnerType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw new JsonException($"Expected a JSON string for enum SettingsServiceResourceOwnerType but got {reader.TokenType}.");
        }

        string? value = reader.GetString();
        return value switch
        {
            "RESOURCE_OWNER_TYPE_UNSPECIFIED" => SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEUNSPECIFIED,
            "RESOURCE_OWNER_TYPE_INSTANCE" => SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEINSTANCE,
            "RESOURCE_OWNER_TYPE_ORG" => SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEORG,
            _ => throw new JsonException($"Unknown value '{value}' for enum SettingsServiceResourceOwnerType.")
        };
    }

    public override void Write(Utf8JsonWriter writer, SettingsServiceResourceOwnerType value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value switch
        {
            SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEUNSPECIFIED => "RESOURCE_OWNER_TYPE_UNSPECIFIED",
            SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEINSTANCE => "RESOURCE_OWNER_TYPE_INSTANCE",
            SettingsServiceResourceOwnerType.RESOURCEOWNERTYPEORG => "RESOURCE_OWNER_TYPE_ORG",
            _ => throw new JsonException($"Unknown value '{value}' for enum SettingsServiceResourceOwnerType.")
        });
    }
}
