// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum SettingsServiceMultiFactorType
{
    [JsonStringEnumMemberName("MULTI_FACTOR_TYPE_UNSPECIFIED")]
    MULTIFACTORTYPEUNSPECIFIED,

    [JsonStringEnumMemberName("MULTI_FACTOR_TYPE_U2F_WITH_VERIFICATION")]
    MULTIFACTORTYPEU2FWITHVERIFICATION,
}
