// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class SettingsServiceDomainSettings : IEquatable<SettingsServiceDomainSettings>
{
    /// <summary>
    /// If enabled, the login name will automatically be suffixed with the domain of the organization.  This ensures that the login name is unique across the instance.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("loginNameIncludesDomain")]
    public bool? LoginNameIncludesDomain { get; set; }

    /// <summary>
    /// If enabled, organization domains must be verified (through an DNS or HTTP challenge) upon creation.  If disabled, organization domains will be created as already verified automatically.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("requireOrgDomainVerification")]
    public bool? RequireOrgDomainVerification { get; set; }

    /// <summary>
    /// If enabled, the SMTP sender address domain must match custom domain on the instance.
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("smtpSenderAddressMatchesInstanceDomain")]
    public bool? SmtpSenderAddressMatchesInstanceDomain { get; set; }

    /// <example>null</example>
    [JsonPropertyName("resourceOwnerType")]
    public SettingsServiceResourceOwnerType? ResourceOwnerType { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(SettingsServiceDomainSettings? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<bool?>.Default.Equals(this.LoginNameIncludesDomain, other.LoginNameIncludesDomain)
                    && EqualityComparer<bool?>.Default.Equals(this.RequireOrgDomainVerification, other.RequireOrgDomainVerification)
                    && EqualityComparer<bool?>.Default.Equals(this.SmtpSenderAddressMatchesInstanceDomain, other.SmtpSenderAddressMatchesInstanceDomain)
                    && EqualityComparer<SettingsServiceResourceOwnerType?>.Default.Equals(this.ResourceOwnerType, other.ResourceOwnerType));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as SettingsServiceDomainSettings);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.LoginNameIncludesDomain);
        hash.Add(this.RequireOrgDomainVerification);
        hash.Add(this.SmtpSenderAddressMatchesInstanceDomain);
        hash.Add(this.ResourceOwnerType);
        return hash.ToHashCode();
    }
}
