// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServicePasswordResetResponse : IEquatable<UserServicePasswordResetResponse>
{
    /// <example>null</example>
    [JsonPropertyName("details")]
    public UserServiceDetails? Details { get; set; }

    /// <summary>
    /// in case the medium was set to return_code, the code will be returned
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("verificationCode")]
    public string? VerificationCode { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServicePasswordResetResponse? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<UserServiceDetails?>.Default.Equals(this.Details, other.Details)
                    && EqualityComparer<string?>.Default.Equals(
                        this.VerificationCode,
                        other.VerificationCode
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServicePasswordResetResponse);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Details);
        hash.Add(this.VerificationCode);
        return hash.ToHashCode();
    }
}
