// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceSearchQuery : IEquatable<UserServiceSearchQuery>
{
    /// <example>null</example>
    [JsonPropertyName("andQuery")]
    public UserServiceAndQuery? AndQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("displayNameQuery")]
    public UserServiceDisplayNameQuery? DisplayNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("emailQuery")]
    public UserServiceEmailQuery? EmailQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("firstNameQuery")]
    public UserServiceFirstNameQuery? FirstNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("inUserEmailsQuery")]
    public UserServiceInUserEmailsQuery? InUserEmailsQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("inUserIdsQuery")]
    public UserServiceInUserIDQuery? InUserIdsQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("lastNameQuery")]
    public UserServiceLastNameQuery? LastNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("loginNameQuery")]
    public UserServiceLoginNameQuery? LoginNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("metadataKeyFilter")]
    public UserServiceMetadataKeyFilter? MetadataKeyFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("metadataValueFilter")]
    public UserServiceMetadataValueFilter? MetadataValueFilter { get; set; }

    /// <example>null</example>
    [JsonPropertyName("nickNameQuery")]
    public UserServiceNickNameQuery? NickNameQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("notQuery")]
    public UserServiceNotQuery? NotQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("orQuery")]
    public UserServiceOrQuery? OrQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("organizationIdQuery")]
    public UserServiceOrganizationIdQuery? OrganizationIdQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("phoneQuery")]
    public UserServicePhoneQuery? PhoneQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("stateQuery")]
    public UserServiceStateQuery? StateQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("typeQuery")]
    public UserServiceTypeQuery? TypeQuery { get; set; }

    /// <example>null</example>
    [JsonPropertyName("userNameQuery")]
    public UserServiceUserNameQuery? UserNameQuery { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceSearchQuery? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<UserServiceAndQuery?>.Default.Equals(
                    this.AndQuery,
                    other.AndQuery
                )
                    && EqualityComparer<UserServiceDisplayNameQuery?>.Default.Equals(
                        this.DisplayNameQuery,
                        other.DisplayNameQuery
                    )
                    && EqualityComparer<UserServiceEmailQuery?>.Default.Equals(
                        this.EmailQuery,
                        other.EmailQuery
                    )
                    && EqualityComparer<UserServiceFirstNameQuery?>.Default.Equals(
                        this.FirstNameQuery,
                        other.FirstNameQuery
                    )
                    && EqualityComparer<UserServiceInUserEmailsQuery?>.Default.Equals(
                        this.InUserEmailsQuery,
                        other.InUserEmailsQuery
                    )
                    && EqualityComparer<UserServiceInUserIDQuery?>.Default.Equals(
                        this.InUserIdsQuery,
                        other.InUserIdsQuery
                    )
                    && EqualityComparer<UserServiceLastNameQuery?>.Default.Equals(
                        this.LastNameQuery,
                        other.LastNameQuery
                    )
                    && EqualityComparer<UserServiceLoginNameQuery?>.Default.Equals(
                        this.LoginNameQuery,
                        other.LoginNameQuery
                    )
                    && EqualityComparer<UserServiceMetadataKeyFilter?>.Default.Equals(
                        this.MetadataKeyFilter,
                        other.MetadataKeyFilter
                    )
                    && EqualityComparer<UserServiceMetadataValueFilter?>.Default.Equals(
                        this.MetadataValueFilter,
                        other.MetadataValueFilter
                    )
                    && EqualityComparer<UserServiceNickNameQuery?>.Default.Equals(
                        this.NickNameQuery,
                        other.NickNameQuery
                    )
                    && EqualityComparer<UserServiceNotQuery?>.Default.Equals(
                        this.NotQuery,
                        other.NotQuery
                    )
                    && EqualityComparer<UserServiceOrQuery?>.Default.Equals(
                        this.OrQuery,
                        other.OrQuery
                    )
                    && EqualityComparer<UserServiceOrganizationIdQuery?>.Default.Equals(
                        this.OrganizationIdQuery,
                        other.OrganizationIdQuery
                    )
                    && EqualityComparer<UserServicePhoneQuery?>.Default.Equals(
                        this.PhoneQuery,
                        other.PhoneQuery
                    )
                    && EqualityComparer<UserServiceStateQuery?>.Default.Equals(
                        this.StateQuery,
                        other.StateQuery
                    )
                    && EqualityComparer<UserServiceTypeQuery?>.Default.Equals(
                        this.TypeQuery,
                        other.TypeQuery
                    )
                    && EqualityComparer<UserServiceUserNameQuery?>.Default.Equals(
                        this.UserNameQuery,
                        other.UserNameQuery
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceSearchQuery);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.AndQuery);
        hash.Add(this.DisplayNameQuery);
        hash.Add(this.EmailQuery);
        hash.Add(this.FirstNameQuery);
        hash.Add(this.InUserEmailsQuery);
        hash.Add(this.InUserIdsQuery);
        hash.Add(this.LastNameQuery);
        hash.Add(this.LoginNameQuery);
        hash.Add(this.MetadataKeyFilter);
        hash.Add(this.MetadataValueFilter);
        hash.Add(this.NickNameQuery);
        hash.Add(this.NotQuery);
        hash.Add(this.OrQuery);
        hash.Add(this.OrganizationIdQuery);
        hash.Add(this.PhoneQuery);
        hash.Add(this.StateQuery);
        hash.Add(this.TypeQuery);
        hash.Add(this.UserNameQuery);
        return hash.ToHashCode();
    }
}
