// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceMachineUser : IEquatable<UserServiceMachineUser>
{
    /// <example>null</example>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <example>null</example>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <example>null</example>
    [JsonPropertyName("hasSecret")]
    public bool? HasSecret { get; set; }

    /// <example>null</example>
    [JsonPropertyName("accessTokenType")]
    public UserServiceAccessTokenType? AccessTokenType { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceMachineUser? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.Name, other.Name)
                    && EqualityComparer<string?>.Default.Equals(this.Description, other.Description)
                    && EqualityComparer<bool?>.Default.Equals(this.HasSecret, other.HasSecret)
                    && EqualityComparer<UserServiceAccessTokenType?>.Default.Equals(this.AccessTokenType, other.AccessTokenType));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceMachineUser);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Name);
        hash.Add(this.Description);
        hash.Add(this.HasSecret);
        hash.Add(this.AccessTokenType);
        return hash.ToHashCode();
    }
}
