// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceSendPasskeyRegistrationLink : IEquatable<UserServiceSendPasskeyRegistrationLink>
{
    /// <summary>
    /// Optionally set a url_template, which will be used in the mail sent by ZITADEL to guide the user to your passkey registration page.  If no template is set, the default ZITADEL url will be used.   The following placeholders can be used: UserID, OrgID, CodeID, Code
    /// </summary>
    /// <example>null</example>
    [JsonPropertyName("urlTemplate")]
    public string? UrlTemplate { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceSendPasskeyRegistrationLink? other)
    {
        return other is not null
            && (ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.UrlTemplate, other.UrlTemplate));
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceSendPasskeyRegistrationLink);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.UrlTemplate);
        return hash.ToHashCode();
    }
}
