// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceRedirectURLs : IEquatable<UserServiceRedirectURLs>
{
    /// <example>null</example>
    [JsonPropertyName("successUrl")]
    public string? SuccessUrl { get; set; }

    /// <example>null</example>
    [JsonPropertyName("failureUrl")]
    public string? FailureUrl { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceRedirectURLs? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<string?>.Default.Equals(this.SuccessUrl, other.SuccessUrl)
                    && EqualityComparer<string?>.Default.Equals(this.FailureUrl, other.FailureUrl)
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceRedirectURLs);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.SuccessUrl);
        hash.Add(this.FailureUrl);
        return hash.ToHashCode();
    }
}
