// <auto-generated/>
// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech
#nullable enable

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum UserServicePersonalAccessTokenFieldName
{
    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED")]
    PERSONALACCESSTOKENFIELDNAMEUNSPECIFIED,

    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE")]
    PERSONALACCESSTOKENFIELDNAMECREATEDDATE,

    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID")]
    PERSONALACCESSTOKENFIELDNAMEID,

    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID")]
    PERSONALACCESSTOKENFIELDNAMEUSERID,

    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID")]
    PERSONALACCESSTOKENFIELDNAMEORGANIZATIONID,

    [JsonStringEnumMemberName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE")]
    PERSONALACCESSTOKENFIELDNAMEEXPIRATIONDATE,
}
