// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceMetadataSearchFilter : IEquatable<UserServiceMetadataSearchFilter>
{
    /// <example>null</example>
    [JsonPropertyName("keyFilter")]
    public UserServiceMetadataKeyFilter? KeyFilter { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceMetadataSearchFilter? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<UserServiceMetadataKeyFilter?>.Default.Equals(
                    this.KeyFilter,
                    other.KeyFilter
                )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceMetadataSearchFilter);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.KeyFilter);
        return hash.ToHashCode();
    }
}
