// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

using System.Text.Json.Serialization;

namespace Zitadel.Client.Models;

public class UserServiceHuman : IEquatable<UserServiceHuman>
{
    /// <example>null</example>
    [JsonPropertyName("profile")]
    public UserServiceProfile? Profile { get; set; }

    /// <example>null</example>
    [JsonPropertyName("email")]
    public UserServiceSetHumanEmail? Email { get; set; }

    /// <example>null</example>
    [JsonPropertyName("phone")]
    public UserServiceSetHumanPhone? Phone { get; set; }

    /// <example>null</example>
    [JsonPropertyName("password")]
    public UserServiceSetPassword? Password { get; set; }

    /// <summary>Value-equality based on all declared fields.</summary>
    public bool Equals(UserServiceHuman? other)
    {
        return other is not null
            && (
                ReferenceEquals(this, other)
                || EqualityComparer<UserServiceProfile?>.Default.Equals(this.Profile, other.Profile)
                    && EqualityComparer<UserServiceSetHumanEmail?>.Default.Equals(
                        this.Email,
                        other.Email
                    )
                    && EqualityComparer<UserServiceSetHumanPhone?>.Default.Equals(
                        this.Phone,
                        other.Phone
                    )
                    && EqualityComparer<UserServiceSetPassword?>.Default.Equals(
                        this.Password,
                        other.Password
                    )
            );
    }

    public override bool Equals(object? obj)
    {
        return Equals(obj as UserServiceHuman);
    }

    public override int GetHashCode()
    {
        HashCode hash = default;
        hash.Add(this.Profile);
        hash.Add(this.Email);
        hash.Add(this.Phone);
        hash.Add(this.Password);
        return hash.ToHashCode();
    }
}
