// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

namespace Zitadel.Client.Errors;

/// <summary>
/// Exception for HTTP 409 Conflict.
/// </summary>
public class ConflictException : ClientException
{
    public ConflictException()
        : this("Conflict") { }

    public ConflictException(string message)
        : this(message, null, null, null) { }

    public ConflictException(string message, Exception innerException)
        : base(message, innerException) { }

    public ConflictException(
        string message,
        Dictionary<string, string>? responseHeaders = null,
        string? responseBody = null,
        object? errorBody = null
    )
        : base(409, message, responseHeaders, responseBody, errorBody) { }
}
