// Zitadel SDK
// The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
//
// The version of the OpenAPI document: 1.0.0
//
// Generated by: https://openapi-generator.tech

namespace Zitadel.Client.Errors;

/// <summary>
/// Exception for HTTP 500 Internal Server Error.
/// </summary>
public class InternalServerErrorException : ServerException
{
    public InternalServerErrorException()
        : this("Internal Server Error") { }

    public InternalServerErrorException(string message)
        : this(message, null, null, null) { }

    public InternalServerErrorException(string message, Exception innerException)
        : base(message, innerException) { }

    public InternalServerErrorException(
        string message,
        Dictionary<string, string>? responseHeaders = null,
        string? responseBody = null,
        object? errorBody = null
    )
        : base(500, message, responseHeaders, responseBody, errorBody) { }
}
